import { defineStore } from 'pinia';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

export const useutf8Store = defineStore('utf8', {
  state: () => ({
    currentLanguage: 'es',
    translations: {
      en: {
        'login.title': 'Sign in to your account',
        'login.email': 'Email address',
        'login.username': 'Username',
        'login.usernamePassword': 'Username or password is incorrect',
        'login.password': 'Password',
        'login.allInputs': 'All fields are required. Please fill in all fields.',
        'login.remember': 'Remember me',
        'login.forgot': 'Forgot your password?',
        'login.submit': 'Sign in',
        'login.loginError': 'Login error',
        'language': 'Language',
        'language.en': 'English',
        'language.es': 'Spanish',
        'language.cat': 'Catalan',
        'language.select': 'Select your language',
        'login.login': 'Login',
        'login.register': 'Register',
        'login.forgotPassword': 'Forgot Password',
        'signup.title': 'Create an account',
        'signup.email': 'Email address',
        'signup.emailExists': 'Email already exists',
        'signup.username': 'Username',
        'signup.usernameError': 'Username is incorrect. Minimum 5 characters, no spaces and maximum 20 characters',
        'signup.usernameExists': 'Username already exists',
        'signup.password': 'Password',
        'signup.confirmPassword': 'Confirm Password',
        'signup.submit': 'Create Account',
        'signup.login': 'Already have an account? Sign in',
        'signup.passwordMismatch': 'Passwords do not match',
        'signup.passwordLength': 'Password must be at least 6 characters long',
        'signup.invalidEmail': 'Invalid email address',
        'signup.emptyFields': 'All fields are required',
        'modal.close': 'Close',
        'modal.error': 'Error',
        'modal.success': 'Success',
        'modal.warning': 'Warning',
        'modal.info': 'Information',
        'modal.confirm': 'Confirm',
        'modal.cancel': 'Cancel',
        'modal.save': 'Save',
        'modal.delete': 'Delete',
        'modal.edit': 'Edit'
      },
      es: {
        'login.title': 'Iniciar sesión',
        'login.email': 'Correo electrónico',
        'login.username': 'Nombre de usuario',
        'login.usernamePassword': 'Nombre de usuario o contraseña incorrectos',
        'login.password': 'Contraseña',
        'login.allInputs': 'Todos los campos son obligatorios. Por favor, completa todos los campos.',
        'login.remember': 'Recordarme',
        'login.forgot': '¿Olvidaste tu contraseña?',
        'login.submit': 'Entrar',
        'login.loginError': 'Error al iniciar sesión',
        'language': 'Idioma',
        'language.en': 'Inglés',
        'language.es': 'Español',
        'language.cat': 'Catalán',
        'language.select': 'Selecciona tu idioma',
        'login.login': 'Iniciar sesión',
        'login.register': 'Registrar',
        'login.forgotPassword': 'Olvidé mi contraseña',
        'signup.title': 'Crear una cuenta',
        'signup.email': 'Correo electrónico',
        'signup.emailExists': 'El correo electrónico ya existe',
        'signup.username': 'Nombre de usuario',
        'signup.usernameError': 'El nombre de usuario es incorrecto. Mínimo 5 caracteres, sin espacios y máximo 20 caracteres',
        'signup.usernameExists': 'El nombre de usuario ya existe',
        'signup.password': 'Contraseña',
        'signup.confirmPassword': 'Confirmar contraseña',
        'signup.submit': 'Crear cuenta',
        'signup.login': '¿Ya tienes una cuenta? Inicia sesión',
        'signup.passwordMismatch': 'Las contraseñas no coinciden',
        'signup.passwordLength': 'La contraseña debe tener al menos 6 caracteres',
        'signup.invalidEmail': 'Correo electrónico no válido',
        'signup.emptyFields': 'Todos los campos son obligatorios',
        'modal.close': 'Cerrar',
        'modal.error': 'Error',
        'modal.success': 'Éxito',
        'modal.warning': 'Advertencia',
        'modal.info': 'Información',
        'modal.confirm': 'Confirmar',
        'modal.cancel': 'Cancelar',
        'modal.save': 'Guardar',
        'modal.delete': 'Eliminar',
        'modal.edit': 'Editar'
      },
      cat: {
        'login.title': 'Iniciar sessió',
        'login.email': 'Correu electrònic',
        'login.username': 'Nom d\'usuari',
        'login.password': 'Contrasenya',
        'login.usernamePassword': 'Nom d\'usuari o contrasenya incorrectes',
        'login.allInputs': 'Tots els camps són obligatoris. Si us plau, completa tots els camps.',
        'login.remember': 'Recorda\'m',
        'login.forgot': 'Has oblidat la teva contrasenya?',
        'login.submit': 'Entrar',
        'login.loginError': 'Error en iniciar sessió',
        'language': 'Idioma',
        'language.en': 'Anglès',
        'language.es': 'Espanyol',
        'language.cat': 'Català',
        'language.select': 'Selecciona el teu idioma',
        'login.login': 'Iniciar sessió',
        'login.register': 'Registrar',
        'login.forgotPassword': 'He oblidat la meva contrasenya',
        'signup.title': 'Crear un compte',
        'signup.email': 'Correu electrònic',
        'signup.emailExists': 'El correu electrònic ja existeix',
        'signup.username': 'Nom d\'usuari',
        'signup.usernameError': 'El nom d\'usuari és incorrecte. Com a mínim 5 caràcters, sense espais i màxim 20 caràcters',
        'signup.usernameExists': 'El nom d\'usuari ja existeix',
        'signup.password': 'Contrasenya',
        'signup.confirmPassword': 'Confirmar contrasenya',
        'signup.submit': 'Crear compte',
        'signup.login': 'Ja tens un compte? Inicia sessió',
        'signup.passwordMismatch': 'Les contrasenyes no coincideixen',
        'signup.passwordLength': 'La contrasenya ha de tenir almenys 6 caràcters',
        'signup.invalidEmail': 'Correu electrònic no vàlid',
        'signup.emptyFields': 'Tots els camps són obligatoris',
        'modal.close': 'Tancar',
        'modal.error': 'Error',
        'modal.success': 'Èxit',
        'modal.warning': 'Advertència',
        'modal.info': 'Informació',
        'modal.confirm': 'Confirmar',
        'modal.cancel': 'Cancel·lar',
        'modal.save': 'Desar',
        'modal.delete': 'Eliminar',
        'modal.edit': 'Editar'
      },
    } as Translations
  }),
  actions: {
    setLanguage(lang: string) {
      this.currentLanguage = lang;
    },
    t(key: string): string {
      return this.translations[this.currentLanguage][key] || key;
    }
  }
});
