import { defineStore } from 'pinia';
import Cookies from 'js-cookie';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

export const useutf8Store = defineStore('utf8', {
  state: () => {
    // Check if language is stored in cookies, otherwise default to Spanish
    const savedLanguage = Cookies.get('language') || 'es';

    return {
      currentLanguage: savedLanguage,
      translations: {
        en: {
          'profile.dashboard': 'Dashboard - Visit Statistics',
          'producto.add.title': 'Add New Product',
          'producto.add.step1': 'Title',
          'producto.add.step2': 'Category',
          'producto.add.step3': 'Images',
          'producto.add.step4': 'Details',
          'producto.titlePlaceholder': 'Enter product title',
          'producto.selectCategory': 'Select a category',
          'producto.addImage': 'Add image',
          'producto.category': 'Category',
          'producto.description': 'Description',
          'common.previous': 'Previous',
          'common.next': 'Next',
          'common.save': 'Save',
          'links.categoria.add': 'Add category',
          'links.categoria.list': 'Category list',
          'links.dashboard': 'Dashboard',
          'links.settings': 'Settings',
          'links.profile': 'Profile',
          'links.help': 'Help',
          'links.logout': 'Logout',
          'links.chat': 'My Chats',
          'links.invoices': 'My Invoices',
          'login.title': 'Sign in to your account',
          'login.email': 'Email address',
          'login.username': 'Username',
          'login.usernamePassword': 'Username or password is incorrect',
          'login.password': 'Password',
          'login.allInputs': 'All fields are required. Please fill in all fields.',
          'login.remember': 'Remember me',
          'login.forgot': 'Forgot your password?',
          'login.submit': 'Sign in',
          'login.loginError': 'Login error',
          'language': 'Language',
          'language.en': 'English',
          'language.es': 'Spanish',
          'language.cat': 'Catalan',
          'language.select': 'Select your language',
          'login.login': 'Login',
          'login.register': 'Register',
          'login.forgotPassword': 'Forgot Password',
          'signup.title': 'Create an account',
          'signup.email': 'Email address',
          'signup.emailExists': 'Email already exists',
          'signup.username': 'Username',
          'signup.usernameError': 'Username is incorrect. Minimum 5 characters, no spaces and maximum 20 characters',
          'signup.usernameExists': 'Username already exists',
          'signup.password': 'Password',
          'signup.confirmPassword': 'Confirm Password',
          'signup.submit': 'Create Account',
          'signup.login': 'Already have an account? Sign in',
          'signup.passwordMismatch': 'Passwords do not match',
          'signup.passwordLength': 'Password must be at least 6 characters long',
          'signup.invalidEmail': 'Invalid email address',
          'signup.emptyFields': 'All fields are required',
          'modal.close': 'Close',
          'modal.error': 'Error',
          'modal.success': 'Success',
          'modal.warning': 'Warning',
          'modal.info': 'Information',
          'modal.confirm': 'Confirm',
          'modal.cancel': 'Cancel',
          'modal.save': 'Save',
          'modal.delete': 'Delete',
          'modal.edit': 'Edit',
          'categoria.title': 'Create Category',
          'categoria.edit': 'Edit Category',
          'categoria.form.title': 'Title',
          'categoria.form.description': 'Description',
          'categoria.form.fields': 'Fields',
          'categoria.form.addField': 'Add Field',
          'categoria.form.fieldPlaceholder': 'Field name',
          'categoria.form.save': 'Save',
          'categoria.form.update': 'Update',
          'categoria.form.cancel': 'Cancel',
          'categoria.form.back': 'Back',
          'categoria.form.field': 'field',
          'categoria.form.fieldsPlural': 'fields',
          'categoria.error.server': 'Server error',
          'categoria.error.unknown': 'Unknown error',
          'categoria.error.loading': 'Error loading category',
          'categoria.error.saving': 'Error saving category',
          'categoria.validation.emptyFields': 'Fields cannot be empty',
          'categoria.success.created': 'Category created successfully',
          'categoria.success.updated': 'Category updated successfully',
          'categoria.list.title': 'Categories List',
          'categoria.list.add': 'Add Category',
          'categoria.list.loading': 'Loading categories...',
          'categoria.list.error': 'Error loading categories:',
          'categoria.list.empty': 'No categories available',
          'categoria.list.delete.title': 'Are you sure?',
          'categoria.list.delete.text': 'This action will permanently delete the category',
          'categoria.list.delete.confirm': 'Yes, delete',
          'categoria.list.delete.cancel': 'Cancel',
          'categoria.list.delete.success': 'Category successfully deleted',
          'categoria.list.delete.error': 'Error deleting category',
          'navigation.static': 'Static Links',
          'navigation.dynamic': 'Context Menu',
          'login.session_expired': 'Session expired. Please log in again.',
          'auth.access_denied': 'Access denied: The role {role} does not have permission to access this page.',
          'auth.login_required': 'Please login to continue.',
          'auth.unexpected_error': 'Unexpected error occurred.',
          'roles.ADMIN': 'Administrator',
          'roles.COMPRADOR': 'Buyer',
          'roles.VENDEDOR': 'Seller',
          'roles.TRABAJADOR': 'Worker',
          'header.welcome': 'Welcome',
          'header.menu': 'Menu',
          'header.toggle_menu': 'Toggle menu',
          'route.home': 'Home',
          'route.login': 'Login',
          'route.signup': 'Sign up',
          'route.profile': 'Profile',
          'route.categories': 'Categories',
          'route.create_category': 'Create Category',
          'route.edit_category': 'Edit Category',
          'error.404': 'Page not found',
          'error.403': 'Forbidden',
          'error.500': 'Server error',
          'error.generic': 'Something went wrong',
          'actions.save': 'Save',
          'actions.cancel': 'Cancel',
          'actions.edit': 'Edit',
          'actions.delete': 'Delete',
          'actions.view': 'View',
          'actions.back': 'Back',
          'actions.next': 'Next',
          'actions.previous': 'Previous',
          'common.loading': 'Loading...',
          'common.error': 'Error',
          'common.success': 'Success',
          'common.warning': 'Warning',
          'common.info': 'Information',
          'producto.title': 'Available Products',
          'producto.price': 'Price',
          'producto.price.hint': 'Enter the price with up to two decimal places (example: 19.99)',
          'producto.details.title': 'Details',
          'producto.brand': 'Brand',
          'producto.state': 'State',
          'producto.stock': 'Stock',
          'producto.stock.available': '{count} available',
          'producto.stock.unavailable': 'Out of stock',
          'producto.action.details': 'View Details',
          'producto.action.buy': 'Buy',
          'producto.action.enable': 'Enable Product',
          'producto.action.disable': 'Disable Product',
          'producto.action.delete': 'Delete',
          'producto.action.ownProduct': 'Your Own Product',
          'producto.action.cantBuyOwn': 'You cannot buy your own product',
          'producto.delete.confirmTitle': 'Delete Product',
          'producto.delete.confirmText': 'Are you sure you want to delete this product? This action cannot be undone.',
          'producto.delete.confirmButton': 'Yes, delete',
          'producto.delete.success': 'Product Deleted',
          'producto.delete.successMessage': 'The product has been successfully deleted.',
          'producto.delete.errorMessage': 'An error occurred while deleting the product. Please try again.',
          'producto.loading': 'Loading products...',
          'producto.empty': 'No products available.',
          'producto.inStock': 'In Stock',
          'producto.lowStock': 'Low Stock',
          'producto.outOfStock': 'Out of Stock',
          'producto.details': 'Details',
          'producto.emptyDescription': 'No products are currently available in our catalog. Please check back later or contact support for more information.',
          'producto.add.success': 'Product Created',
          'producto.add.successMessage': 'Your product has been created successfully.',
          'producto.add.error': 'Error',
          'producto.add.errorMessage': 'There was an error creating your product. Please try again.',
          'producto.validation.error': 'Validation Error',
          'producto.validation.titleRequired': 'Please enter a product title.',
          'producto.validation.categoryRequired': 'Please select a category.',
          'producto.validation.imageRequired': 'Please upload at least one product image.',
          'producto.validation.brandRequired': 'Please enter a brand name.',
          'producto.validation.descriptionRequired': 'Please enter a product description.',
          'producto.validation.priceRequired': 'Please enter a valid price (greater than 0).',
          'producto.validation.priceInvalid': 'Price must be at least 0.01',
          'producto.validation.stockInvalid': 'Stock cannot be negative.',
          'producto.validation.categoryFieldsRequired': 'Please complete all category-specific fields.',
          'producto.estado': 'Condition',
          'producto.estados.NUEVO': 'New',
          'producto.estados.COMONUEVO': 'Like New',
          'producto.estados.BUENESTADO': 'Good Condition',
          'producto.estados.ACEPTABLE': 'Acceptable',
          'producto.estados.USADO': 'Used',
          'producto.estados.REPARADO': 'Repaired',
          'producto.estados.REPARACIONESNECESARIAS': 'Repairs Needed',
          'producto.estados.DESCONOCIDO': 'Unknown',
          'producto.add.back': 'Back to Products',
          'producto.images': 'Product Images',
          'producto.direccion': 'Location',
          'producto.activo': 'Active',
          'producto.destacado': 'Featured',
          'producto.category.fields': 'Category Specific Fields',
          'common.ok': 'OK',
          'producto.direccionPlaceholder': 'Search city or location...',
          'producto.usarUbicacionActual': 'Use my location',
          'producto.ubicacion.obteniendo': 'Getting location',
          'producto.ubicacion.espere': 'Please wait...',
          'producto.ubicacion.errorTitle': 'Location Error',
          'producto.ubicacion.errorMessage': 'Could not get your current location. Please check your device permissions.',
          'producto.ubicacion.noSupported': 'Geolocation is not supported by your browser.',
          'producto.status.activated': 'Product has been successfully activated',
          'producto.status.deactivated': 'Product has been successfully deactivated',
          'producto.status.toggleError': 'An error occurred while changing product status',
          'producto.details.loading': 'Loading product details...',
          'common.notAvailable': 'Not available',
          'common.yes': 'Yes',
          'common.no': 'No',
          'common.dates': 'Dates',
          'common.createdOn': 'Created on',
          'common.modifiedOn': 'Modified on',
          'common.publishedOn': 'Published on',
          'common.cancel': 'Cancel',
          'producto.edit.title': 'Edit Product',
          'producto.edit.success': 'Product Updated',
          'producto.edit.successMessage': 'Your product has been updated successfully.',
          'producto.edit.error': 'Update Error',
          'producto.edit.errorMessage': 'There was an error updating your product. Please try again.',
          'producto.edit.loadError': 'Load Error',
          'producto.edit.loadErrorMessage': 'There was an error loading the product data. Please try again.',
          'common.update': 'Update',
          'producto.action.edit': 'Edit Product',
          'producto.offerTitle': 'Make an Offer',
          'producto.makeOffer': 'Your offer',
          'producto.offerHint': 'Enter the amount you would like to offer for this product',
          'producto.sendOffer': 'Send Offer',
          'producto.offerMessage': 'I would like to offer {offerAmount} for the product: {productTitle}',
          'chat.createError': 'Could not create chat. Please try again.',
          'chat.title': 'Chat with Seller',
          'chat.title.asSeller': 'Chat with Buyer',
          'chat.withUser': 'Chatting with {userName}',
          'chat.withUser.buyer': 'Buyer: {userName}',
          'chat.withUser.seller': 'Seller: {userName}',
          'chat.noMessages': 'No messages yet. Start the conversation!',
          'chat.typePlaceholder': 'Type a message...',
          'chat.send': 'Send',
          'chat.loading': 'Loading messages...',
          'chat.error': 'Error loading chat',
          'chat.start': 'Start Chat',
          'chat.loginRequired': 'Please login to chat with the seller',
          'chat.contactSeller': 'Contact Seller',
          'chat.buyerInitMessage': 'Hi, I\'m interested in this product.',
          'chat.list.title': 'My Chats',
          'chat.list.empty': 'No chats found',
          'chat.list.emptyDescription': 'You don\'t have any active conversations. Browse products and contact a seller to start chatting.',
          'chat.list.browseProducts': 'Browse Products',
          'chat.viewChat': 'View Chat',
          'chat.unknownProduct': 'Unknown Product',
          'chat.list.loadError': 'Error loading your chats',
          'profile.title': 'User Profile',
          'profile.account_info': 'Account Information',
          'profile.username': 'Username',
          'profile.email': 'Email',
          'profile.role': 'Role',
          'profile.edit_profile': 'Edit Profile',
          'profile.new_password': 'New Password',
          'profile.confirm_password': 'Confirm Password',
          'profile.password_note': 'Leave blank to keep your current password',
          'profile.save': 'Save Changes',
          'profile.cancel': 'Cancel',
          'profile.account_actions': 'Account Actions',
          'profile.your_products': 'Your Products',
          'profile.add_product': 'Add New Product',
          'profile.admin_actions': 'Admin Actions',
          'profile.manage_categories': 'Manage Categories',
          'profile.create_category': 'Create Category',
          'profile.communication': 'Communication',
          'profile.view_chats': 'View My Chats',
          'profile.logout': 'Logout',
          'profile.not_logged_in': 'Not Logged In',
          'profile.login_required_message': 'You need to log in to view your profile',
          'profile.login': 'Login',
          'profile.signup': 'Sign Up',
          'profile.ok': 'OK',
          'profile.passwords_dont_match': 'Passwords do not match',
          'profile.invalid_email': 'Please enter a valid email address',
          'profile.update_success': 'Profile updated successfully',
          'profile.update_error': 'Error updating profile',
          'profile.login_error': 'Error checking login status',
          'profile.back_to_login': 'Back to Login',
          'profile.description': 'Description',
          'profile.description_placeholder': 'Write a brief description about yourself...',
          'profile.profile_image': 'Profile Image',
          'profile.social_links': 'Social Links',
          'profile.add_social_link': 'Add Social Link',
          'profile.no_description': 'No description provided',
          'profile.user_profile': 'User Profile',
          'profile.user_products': '{username}\'s Products',
          'profile.view_profile': 'View Profile',
          'profile.view_product': 'View Product',
          'profile.send_message': 'Send Message',
          'profile.user_not_found': 'User Not Found',
          'profile.user_not_found_message': 'The user you are looking for does not exist or has been removed.',
          'profile.user_id_required': 'User ID is required',
          'profile.load_error': 'Error loading user profile',
          'profile.no_products_for_chat': 'This user does not have any products to chat about.',
          'producto.similarProducts': 'Similar Products',
          'producto.filters.title': 'Filter Products',
          'producto.filters.searchPlaceholder': 'Search by name, brand, description...',
          'producto.filters.category': 'Category',
          'producto.filters.state': 'Condition',
          'producto.filters.location': 'Location',
          'producto.filters.priceRange': 'Price Range',
          'producto.filters.allCategories': 'All Categories',
          'producto.filters.allStates': 'All Conditions',
          'producto.filters.allLocations': 'All Locations',
          'producto.filters.min': 'Min',
          'producto.filters.max': 'Max',
          'producto.resultsFound': 'results found',
          'producto.resetFilters': 'Reset Filters',
          'producto.emptyFilters': 'No products match your filters',
          'producto.emptyFiltersDescription': 'Try adjusting your search criteria or browse all products',
          'producto.priceRange': 'Price Range',
          'links.producto.add': 'Add Product',
          'profile.subscription': 'Subscription',
          'profile.subscribe': 'Subscribe Premium',
          'profile.processing': 'Processing...',
          'profile.subscription_success': 'Payment successfully completed',
          'profile.subscription_cancelled': 'Payment cancelled',
          'profile.subscription_error': 'An error occurred while processing your payment',
          'profile.subscription_url_error': 'Invalid session URL received',
          'profile.premium_subscription': 'Premium Subscription',
          'profile.premium_description': 'Upgrade to premium to access exclusive features and benefits.',
          'profile.premium_benefits': 'Premium Benefits',
          'profile.premium_benefit1': 'Highlighted product listings',
          'profile.premium_benefit2': 'Priority customer support',
          'profile.premium_benefit3': 'Advanced analytics',
          'profile.subscription_success_message': 'Your account has been upgraded to Premium',
          'profile.subscription_cancelled_message': 'You have cancelled the payment process',
          'profile.subscription_update_error': 'Could not update your Premium status',
          'profile.promo_code': 'Promotional Code',
          'profile.promo_code_placeholder': 'Enter your promo code',
          'profile.have_promo': 'Have a promotional code?',
          'profile.hide_promo': 'Hide promotional code',
          'profile.promo_code_valid': 'Promo code applied',
          'profile.promo_code_invalid': 'Invalid promo code',
          'profile.promo_code_empty': 'Please enter a promo code',
          'profile.promo_code_error': 'Error validating promo code',
          'common.apply': 'Apply',
          'profile.subscription_options': 'Subscription Options',
          'profile.subscription_options_desc': 'Choose a subscription option to become a seller.',
          'profile.free_trial': 'Free Trial',
          'profile.free_trial_desc': 'Get access to seller features for 30 days at no cost.',
          'profile.free_trial_success': 'Free Trial Activated',
          'profile.free_trial_success_message': 'Your account has been upgraded to seller for 30 days.',
          'profile.premium_desc': 'Subscribe to get all premium features.',
          'estadisticas.title': 'Product Statistics',
          'estadisticas.backToDashboard': 'Back to Dashboard',
          'estadisticas.loading': 'Loading product statistics...',
          'estadisticas.error': 'Error loading product statistics',
          'estadisticas.brand': 'Brand',
          'estadisticas.model': 'Model',
          'estadisticas.condition': 'Condition',
          'estadisticas.price': 'Price',
          'estadisticas.totalVisits': 'Total Visits',
          'estadisticas.monthlyVisits': 'Monthly Visits',
          'estadisticas.visitDetails': 'Visit Details by Month',
          'estadisticas.noData': 'No visit data recorded',
          'estadisticas.table.month': 'Month',
          'estadisticas.table.year': 'Year',
          'estadisticas.table.visits': 'Visits',
          'estadisticas.table.lastUpdate': 'Last Update',
          'estadisticas.noVisits': 'No visits recorded for this product',
          'dashboard.title': 'Dashboard - Visit Statistics',
          'dashboard.totalProducts': 'Total Products',
          'dashboard.totalVisits': 'Total Visits',
          'dashboard.monthlyAverage': 'Monthly Average',
          'dashboard.monthlyVisits': 'Monthly Visits',
          'dashboard.topProducts': 'Most Visited Products',
          'dashboard.noProducts': 'No products with recorded visits',
          'dashboard.viewProduct': 'View Product',
          'dashboard.year': 'Year',
          'dashboard.visits': 'Visits',
          'dashboard.refresh': 'Refresh',
          'dashboard.profile': 'Profile',
          'months.january': 'January',
          'months.february': 'February',
          'months.march': 'March',
          'months.april': 'April',
          'months.may': 'May',
          'months.june': 'June',
          'months.july': 'July',
          'months.august': 'August',
          'months.september': 'September',
          'months.october': 'October',
          'months.november': 'November',
          'months.december': 'December',
          'chat.delete': 'Delete Chat',
          'chat.delete.confirm': 'Are you sure you want to delete this chat? This action cannot be undone.',
          'chat.delete.success': 'Chat deleted successfully',
          'chat.delete.error': 'Error deleting chat',
          'chat.markAsSold': 'Mark as Sold',
          'chat.markAsSold.confirm': 'How many units do you want to sell?',
          'chat.markAsSold.quantity': 'Quantity to sell',
          'chat.markAsSold.success': 'Product marked as sold successfully',
          'chat.markAsSold.error': 'Error marking product as sold',
          'chat.productNotFound': 'Product not found',
          'profile.invoices': 'Invoices',
          'invoice.as_buyer': 'Purchases',
          'invoice.as_seller': 'Sales',
          'invoice.no_invoices': 'No invoices found',
          'invoice.loading_error': 'Error loading invoices',
          'invoice.product': 'Product',
          'invoice.quantity': 'Quantity',
          'invoice.amount': 'Amount',
          'invoice.date': 'Date',
          'invoice.status': 'Status',
          'invoice.actions': 'Actions',
          'invoice.view_details': 'View details',
          'invoice.details': 'Invoice details',
          'invoice.invoice_id': 'Invoice ID',
          'invoice.unit_price': 'Unit price',
          'invoice.subtotal': 'Subtotal',
          'invoice.iva': 'VAT',
          'invoice.total': 'Total',
          'invoice.notes': 'Additional notes',
          'invoice.status.pendiente': 'Pending',
          'invoice.status.pagada': 'Paid',
          'invoice.status.cancelada': 'Cancelled',
          'invoice.status.emitida': 'Issued',
          'invoice.title': 'My Invoices',
          'profile.view_invoices': 'View My Invoices',
          'common.close': 'Close',
          'profile.username_changed_relogin': 'Username changed. You will be logged in again.',
          'profile.relogin_required': 'Re-login Required',
          'profile.username_changed_enter_password': 'Your username was changed. Please enter your password to log in with the new username.',
          'common.login': 'Login',
        },
        es: {
          'profile.dashboard': 'Dashboard - Estadísticas de Visitas',
          'producto.add.title': 'Añadir Nuevo Producto',
          'producto.add.step1': 'Título',
          'producto.add.step2': 'Categoría',
          'producto.add.step3': 'Imágenes',
          'producto.add.step4': 'Detalles',
          'producto.titlePlaceholder': 'Introduce el título del producto',
          'producto.selectCategory': 'Selecciona una categoría',
          'producto.addImage': 'Añadir imagen',
          'producto.category': 'Categoría',
          'producto.description': 'Descripción',
          'common.previous': 'Anterior',
          'common.next': 'Siguiente',
          'common.save': 'Guardar',
          'links.categoria.add': 'Añadir categoría',
          'links.categoria.list': 'Lista de categorías',
          'links.dashboard': 'Panel de control',
          'links.settings': 'Configuración',
          'links.profile': 'Perfil',
          'links.help': 'Ayuda',
          'links.logout': 'Cerrar sesión',
          'links.chat': 'Mis Chats',
          'links.invoices': 'Mis Facturas',
          'login.title': 'Iniciar sesión',
          'login.email': 'Correo electrónico',
          'login.username': 'Nombre de usuario',
          'login.usernamePassword': 'Nombre de usuario o contraseña incorrectos',
          'login.password': 'Contraseña',
          'login.allInputs': 'Todos los campos son obligatorios. Por favor, completa todos los campos.',
          'login.remember': 'Recordarme',
          'login.forgot': '¿Olvidaste tu contraseña?',
          'login.submit': 'Entrar',
          'login.loginError': 'Error al iniciar sesión',
          'language': 'Idioma',
          'language.en': 'Inglés',
          'language.es': 'Español',
          'language.cat': 'Catalán',
          'language.select': 'Selecciona tu idioma',
          'login.login': 'Iniciar sesión',
          'login.register': 'Registrar',
          'login.forgotPassword': 'Olvidé mi contraseña',
          'signup.title': 'Crear una cuenta',
          'signup.email': 'Correo electrónico',
          'signup.emailExists': 'El correo electrónico ya existe',
          'signup.username': 'Nombre de usuario',
          'signup.usernameError': 'El nombre de usuario es incorrecto. Mínimo 5 caracteres, sin espacios y máximo 20 caracteres',
          'signup.usernameExists': 'El nombre de usuario ya existe',
          'signup.password': 'Contraseña',
          'signup.confirmPassword': 'Confirmar contraseña',
          'signup.submit': 'Crear cuenta',
          'signup.login': '¿Ya tienes una cuenta? Inicia sesión',
          'signup.passwordMismatch': 'Las contraseñas no coinciden',
          'signup.passwordLength': 'La contraseña debe tener al menos 6 caracteres',
          'signup.invalidEmail': 'Correo electrónico no válido',
          'signup.emptyFields': 'Todos los campos son obligatorios',
          'modal.close': 'Cerrar',
          'modal.error': 'Error',
          'modal.success': 'Éxito',
          'modal.warning': 'Advertencia',
          'modal.info': 'Información',
          'modal.confirm': 'Confirmar',
          'modal.cancel': 'Cancelar',
          'modal.save': 'Guardar',
          'modal.delete': 'Eliminar',
          'modal.edit': 'Editar',
          'categoria.title': 'Crear Categoría',
          'categoria.edit': 'Editar Categoría',
          'categoria.form.title': 'Título',
          'categoria.form.description': 'Descripción',
          'categoria.form.fields': 'Campos',
          'categoria.form.addField': 'Añadir Campo',
          'categoria.form.fieldPlaceholder': 'Nombre del campo',
          'categoria.form.save': 'Guardar',
          'categoria.form.update': 'Actualizar',
          'categoria.form.cancel': 'Cancelar',
          'categoria.form.back': 'Volver',
          'categoria.form.field': 'campo',
          'categoria.form.fieldsPlural': 'campos',
          'categoria.error.server': 'Error del servidor',
          'categoria.error.unknown': 'Error desconocido',
          'categoria.error.loading': 'Error al cargar la categoría',
          'categoria.error.saving': 'Error al guardar la categoría',
          'categoria.validation.emptyFields': 'Los campos no pueden estar vacíos',
          'categoria.success.created': 'Categoría creada correctamente',
          'categoria.success.updated': 'Categoría actualizada correctamente',
          'categoria.list.title': 'Lista de Categorías',
          'categoria.list.add': 'Añadir Categoría',
          'categoria.list.loading': 'Cargando categorías...',
          'categoria.list.error': 'Error al cargar las categorías:',
          'categoria.list.empty': 'No hay categorías disponibles',
          'categoria.list.delete.title': '¿Está seguro?',
          'categoria.list.delete.text': 'Esta acción eliminará la categoría permanentemente',
          'categoria.list.delete.confirm': 'Sí, eliminar',
          'categoria.list.delete.cancel': 'Cancelar',
          'categoria.list.delete.success': 'Categoría eliminada exitosamente',
          'categoria.list.delete.error': 'Error al eliminar la categoría',
          'navigation.static': 'Enlaces Estáticos',
          'navigation.dynamic': 'Menú Contextual',
          'login.session_expired': 'Sesión expirada. Por favor, inicie sesión de nuevo.',
          'auth.access_denied': 'Acceso denegado: El rol {role} no tiene permisos para acceder a esta página.',
          'auth.login_required': 'Inicia sesión para continuar.',
          'auth.unexpected_error': 'Ha ocurrido un error inesperado.',
          'roles.ADMIN': 'Administrador',
          'roles.COMPRADOR': 'Comprador',
          'roles.VENDEDOR': 'Vendedor',
          'roles.TRABAJADOR': 'Trabajador',
          'header.welcome': 'Bienvenido',
          'header.menu': 'Menú',
          'header.toggle_menu': 'Alternar menú',
          'route.home': 'Inicio',
          'route.login': 'Iniciar sesión',
          'route.signup': 'Registrarse',
          'route.profile': 'Perfil',
          'route.categories': 'Categorías',
          'route.create_category': 'Crear Categoría',
          'route.edit_category': 'Editar Categoría',
          'error.404': 'Página no encontrada',
          'error.403': 'Acceso prohibido',
          'error.500': 'Error del servidor',
          'error.generic': 'Algo salió mal',
          'actions.save': 'Guardar',
          'actions.cancel': 'Cancelar',
          'actions.edit': 'Editar',
          'actions.delete': 'Eliminar',
          'actions.view': 'Ver',
          'actions.back': 'Volver',
          'actions.next': 'Siguiente',
          'actions.previous': 'Anterior',
          'common.loading': 'Cargando...',
          'common.error': 'Error',
          'common.success': 'Éxito',
          'common.warning': 'Advertencia',
          'common.info': 'Información',
          'producto.title': 'Productos Disponibles',
          'producto.price': 'Precio',
          'producto.price.hint': 'Introduce el precio con hasta dos decimales (ejemplo: 19.99)',
          'producto.details.title': 'Detalles',
          'producto.brand': 'Marca',
          'producto.state': 'Estado',
          'producto.stock': 'Stock',
          'producto.stock.available': '{count} disponibles',
          'producto.stock.unavailable': 'Sin stock',
          'producto.action.details': 'Ver Detalles',
          'producto.action.buy': 'Comprar',
          'producto.action.enable': 'Activar Producto',
          'producto.action.disable': 'Desactivar Producto',
          'producto.action.delete': 'Eliminar',
          'producto.action.ownProduct': 'Tu Propio Producto',
          'producto.action.cantBuyOwn': 'No puedes comprar tu propio producto',
          'producto.offerTitle': 'Hacer una Oferta',
          'producto.makeOffer': 'Tu oferta',
          'producto.offerHint': 'Introduce el importe que quieres ofrecer por este producto',
          'producto.sendOffer': 'Enviar Oferta',
          'producto.offerMessage': 'Me gustaría ofrecer {offerAmount} por el producto: {productTitle}',
          'chat.createError': 'No se pudo crear el chat. Por favor, inténtalo de nuevo.',
          'chat.title': 'Chat con el Vendedor',
          'chat.title.asSeller': 'Chat con el Comprador',
          'chat.withUser': 'Chateando con {userName}',
          'chat.withUser.buyer': 'Comprador: {userName}',
          'chat.withUser.seller': 'Vendedor: {userName}',
          'chat.noMessages': 'No hay mensajes aún. ¡Inicia la conversación!',
          'chat.typePlaceholder': 'Escribe un mensaje...',
          'chat.send': 'Enviar',
          'chat.loading': 'Cargando mensajes...',
          'chat.error': 'Error al cargar el chat',
          'chat.start': 'Iniciar Chat',
          'chat.loginRequired': 'Por favor, inicia sesión para chatear con el vendedor',
          'chat.contactSeller': 'Contactar al Vendedor',
          'chat.buyerInitMessage': 'Hola, estoy interesado en este producto.',
          'chat.list.title': 'Mis Chats',
          'chat.list.empty': 'No se encontraron chats',
          'chat.list.emptyDescription': 'No tienes conversaciones activas. Explora productos y contacta con un vendedor para comenzar a chatear.',
          'chat.list.browseProducts': 'Explorar Productos',
          'chat.viewChat': 'Ver Chat',
          'chat.unknownProduct': 'Producto Desconocido',
          'chat.list.loadError': 'Error al cargar tus chats',
          'profile.title': 'Perfil de Usuario',
          'profile.account_info': 'Información de la Cuenta',
          'profile.username': 'Nombre de Usuario',
          'profile.email': 'Correo Electrónico',
          'profile.role': 'Rol',
          'profile.edit_profile': 'Editar Perfil',
          'profile.new_password': 'Nueva Contraseña',
          'profile.confirm_password': 'Confirmar Contraseña',
          'profile.password_note': 'Deja en blanco para mantener tu contraseña actual',
          'profile.save': 'Guardar Cambios',
          'profile.cancel': 'Cancelar',
          'profile.account_actions': 'Acciones de Cuenta',
          'profile.your_products': 'Tus Productos',
          'profile.add_product': 'Añadir Nuevo Producto',
          'profile.admin_actions': 'Acciones de Administrador',
          'profile.manage_categories': 'Gestionar Categorías',
          'profile.create_category': 'Crear Categoría',
          'profile.communication': 'Comunicación',
          'profile.view_chats': 'Ver Mis Chats',
          'profile.view_invoices': 'Ver Mis Facturas',
          'invoice.title': 'Mis Facturas',
          'profile.logout': 'Cerrar Sesión',
          'profile.not_logged_in': 'No Has Iniciado Sesión',
          'profile.login_required_message': 'Necesitas iniciar sesión para ver tu perfil',
          'profile.login': 'Iniciar Sesión',
          'profile.signup': 'Registrarse',
          'profile.ok': 'Aceptar',
          'profile.passwords_dont_match': 'Las contraseñas no coinciden',
          'profile.invalid_email': 'Por favor, introduce un correo electrónico válido',
          'profile.update_success': 'Perfil actualizado con éxito',
          'profile.update_error': 'Error al actualizar el perfil',
          'profile.login_error': 'Error al verificar el estado de inicio de sesión',
          'profile.back_to_login': 'Volver a Iniciar Sesión',
          'profile.description': 'Descripción',
          'profile.description_placeholder': 'Escribe una breve descripción sobre ti...',
          'profile.profile_image': 'Imagen de Perfil',
          'profile.social_links': 'Redes Sociales',
          'profile.add_social_link': 'Añadir Red Social',
          'profile.no_description': 'Sin descripción',
          'profile.user_profile': 'Perfil de Usuario',
          'profile.user_products': 'Productos de {username}',
          'profile.view_profile': 'Ver Perfil',
          'profile.view_product': 'Ver Producto',
          'profile.send_message': 'Enviar Mensaje',
          'profile.user_not_found': 'Usuario No Encontrado',
          'profile.user_not_found_message': 'El usuario que buscas no existe o ha sido eliminado.',
          'profile.user_id_required': 'Se requiere ID de usuario',
          'profile.load_error': 'Error al cargar el perfil de usuario',
          'profile.no_products_for_chat': 'Este usuario no tiene productos para chatear.',
          'producto.similarProducts': 'Productos Similares',
          'producto.filters.title': 'Filtrar Productos',
          'producto.filters.searchPlaceholder': 'Buscar por nombre, marca, descripción...',
          'producto.filters.category': 'Categoría',
          'producto.filters.state': 'Estado',
          'producto.filters.location': 'Ubicación',
          'producto.filters.priceRange': 'Rango de Precio',
          'producto.filters.allCategories': 'Todas las Categorías',
          'producto.filters.allStates': 'Todos los Estados',
          'producto.filters.allLocations': 'Todas las Ubicaciones',
          'producto.filters.min': 'Mín',
          'producto.filters.max': 'Máx',
          'producto.resultsFound': 'resultados encontrados',
          'producto.resetFilters': 'Reiniciar Filtros',
          'producto.emptyFilters': 'Ningún producto coincide con tus filtros',
          'producto.emptyFiltersDescription': 'Intenta ajustar tus criterios de búsqueda o navega por todos los productos',
          'producto.priceRange': 'Rango de Precio',
          'links.producto.add': 'Añadir Producto',
          'profile.subscription': 'Suscripción',
          'profile.subscribe': 'Suscribirse Premium',
          'profile.processing': 'Procesando...',
          'profile.subscription_success': 'Pago realizado con éxito',
          'profile.subscription_cancelled': 'Pago cancelado',
          'profile.subscription_error': 'Ha ocurrido un error al procesar tu pago',
          'profile.subscription_url_error': 'URL de sesión inválida recibida',
          'profile.premium_subscription': 'Suscripción Premium',
          'profile.premium_description': 'Actualiza a premium para acceder a características y beneficios exclusivos.',
          'profile.premium_benefits': 'Beneficios Premium',
          'profile.premium_benefit1': 'Listados de productos destacados',
          'profile.premium_benefit2': 'Soporte prioritario',
          'profile.premium_benefit3': 'Analíticas avanzadas',
          'profile.subscription_success_message': 'Tu cuenta ha sido actualizada a Premium',
          'profile.subscription_cancelled_message': 'Has cancelado el proceso de pago',
          'profile.subscription_update_error': 'No se pudo actualizar tu estado Premium',
          'profile.promo_code': 'Código Promocional',
          'profile.promo_code_placeholder': 'Introduce tu código promocional',
          'profile.have_promo': '¿Tienes un código promocional?',
          'profile.hide_promo': 'Ocultar código promocional',
          'profile.promo_code_valid': 'Código promocional aplicado',
          'profile.promo_code_invalid': 'Código promocional inválido',
          'profile.promo_code_empty': 'Por favor, introduce un código promocional',
          'profile.promo_code_error': 'Error al validar el código promocional',
          'common.apply': 'Aplicar',
          'profile.subscription_options': 'Opciones de Suscripción',
          'profile.subscription_options_desc': 'Elige una opción de suscripción para convertirte en vendedor.',
          'profile.free_trial': 'Prueba Gratuita',
          'profile.free_trial_desc': 'Obtén acceso a funciones de vendedor durante 30 días sin costo.',
          'profile.free_trial_success': 'Prueba Gratuita Activada',
          'profile.free_trial_success_message': 'Tu cuenta ha sido actualizada a vendedor por 30 días.',
          'profile.premium_desc': 'Subscríbete para obtener todas las funciones premium.',
          'estadisticas.title': 'Estadísticas del Producto',
          'estadisticas.backToDashboard': 'Volver al Dashboard',
          'estadisticas.loading': 'Cargando estadísticas del producto...',
          'estadisticas.error': 'Error al cargar las estadísticas',
          'estadisticas.brand': 'Marca',
          'estadisticas.model': 'Modelo',
          'estadisticas.condition': 'Estado',
          'estadisticas.price': 'Precio',
          'estadisticas.totalVisits': 'Visitas Totales',
          'estadisticas.monthlyVisits': 'Visitas Mensuales',
          'estadisticas.visitDetails': 'Detalles de Visitas por Mes',
          'estadisticas.noData': 'No hay datos de visitas registrados',
          'estadisticas.table.month': 'Mes',
          'estadisticas.table.year': 'Año',
          'estadisticas.table.visits': 'Visitas',
          'estadisticas.table.lastUpdate': 'Última Actualización',
          'estadisticas.noVisits': 'No hay visitas registradas para este producto',
          'dashboard.title': 'Dashboard - Estadísticas de Visitas',
          'dashboard.totalProducts': 'Total de Productos',
          'dashboard.totalVisits': 'Total de Visitas',
          'dashboard.monthlyAverage': 'Promedio Mensual',
          'dashboard.monthlyVisits': 'Visitas Mensuales',
          'dashboard.topProducts': 'Productos más visitados',
          'dashboard.noProducts': 'No hay productos con visitas registradas',
          'dashboard.viewProduct': 'Ver Producto',
          'dashboard.year': 'Año',
          'dashboard.visits': 'Visitas',
          'dashboard.refresh': 'Actualizar',
          'dashboard.profile': 'Perfil',
          'months.january': 'Enero',
          'months.february': 'Febrero',
          'months.march': 'Marzo',
          'months.april': 'Abril',
          'months.may': 'Mayo',
          'months.june': 'Junio',
          'months.july': 'Julio',
          'months.august': 'Agosto',
          'months.september': 'Septiembre',
          'months.october': 'Octubre',
          'months.november': 'Noviembre',
          'months.december': 'Diciembre',
          'chat.delete': 'Eliminar Chat',
          'chat.delete.confirm': '¿Estás seguro de que quieres eliminar este chat?',
          'chat.delete.success': 'Chat eliminado con éxito',
          'chat.delete.error': 'Error al eliminar el chat',
          'chat.markAsSold': 'Marcar como Vendido',
          'chat.markAsSold.confirm': '¿Cuántas unidades quieres vender?',
          'chat.markAsSold.quantity': 'Cantidad a vender',
          'chat.markAsSold.success': 'Producto marcado como vendido con éxito',
          'chat.markAsSold.error': 'Error al marcar el producto como vendido',
          'chat.productNotFound': 'Producto no encontrado o ya no disponible',
          'profile.invoices': 'Facturas',
          'invoice.as_buyer': 'Compras',
          'invoice.as_seller': 'Ventas',
          'invoice.no_invoices': 'No se encontraron facturas',
          'invoice.loading_error': 'Error al cargar las facturas',
          'invoice.product': 'Producto',
          'invoice.quantity': 'Cantidad',
          'invoice.amount': 'Monto',
          'invoice.date': 'Fecha',
          'invoice.status': 'Estado',
          'invoice.actions': 'Acciones',
          'invoice.view_details': 'Ver detalles',
          'invoice.details': 'Detalles de la Factura',
          'invoice.invoice_id': 'ID de Factura',
          'invoice.unit_price': 'Precio Unitario',
          'invoice.subtotal': 'Subtotal',
          'invoice.iva': 'IVA',
          'invoice.total': 'Total',
          'invoice.notes': 'Notas Adicionales',
          'invoice.status.pendiente': 'Pendiente',
          'invoice.status.pagada': 'Pagada',
          'invoice.status.cancelada': 'Cancelada',
          'invoice.status.emitida': 'Emitida',
          'common.close': 'Cerrar',
          'profile.username_changed_relogin': 'Nombre de usuario cambiado. Se iniciará sesión nuevamente.',
          'profile.relogin_required': 'Reinicio de sesión requerido',
          'profile.username_changed_enter_password': 'Tu nombre de usuario ha cambiado. Por favor, introduce tu contraseña para iniciar sesión con el nuevo nombre de usuario.',
          'common.login': 'Iniciar sesión',
        },
        cat: {
          'profile.dashboard': 'Tauler - Estadístiques de Visites',
          'producto.add.title': 'Afegir Nou Producte',
          'producto.add.step1': 'Títol',
          'producto.add.step2': 'Categoria',
          'producto.add.step3': 'Imatges',
          'producto.add.step4': 'Detalls',
          'producto.titlePlaceholder': 'Introdueix el títol del producte',
          'producto.selectCategory': 'Selecciona una categoria',
          'producto.addImage': 'Afegir imatge',
          'producto.category': 'Categoria',
          'producto.description': 'Descripció',
          'common.previous': 'Anterior',
          'common.next': 'Següent',
          'common.save': 'Desar',
          'links.categoria.add': 'Afegir categoria',
          'links.categoria.list': 'Llista de categories',
          'links.dashboard': 'Tauler de control',
          'links.settings': 'Configuració',
          'links.profile': 'Perfil',
          'links.help': 'Ajuda',
          'links.logout': 'Tancar sessió',
          'links.chat': 'Els meus Xats',
          'links.invoices': 'Les meves Factures',
          'login.title': 'Iniciar sessió',
          'login.email': 'Correu electrònic',
          'login.username': 'Nom d\'usuari',
          'login.password': 'Contrasenya',
          'login.usernamePassword': 'Nom d\'usuari o contrasenya incorrectes',
          'login.allInputs': 'Tots els camps són obligatoris. Si us plau, completa tots els camps.',
          'login.remember': 'Recorda\'m',
          'login.forgot': 'Has oblidat la teva contrasenya?',
          'login.submit': 'Entrar',
          'login.loginError': 'Error en iniciar sessió',
          'language': 'Idioma',
          'language.en': 'Anglès',
          'language.es': 'Español',
          'language.cat': 'Català',
          'language.select': 'Selecciona el teu idioma',
          'login.login': 'Iniciar sessió',
          'login.register': 'Registrar',
          'login.forgotPassword': 'He oblidat la meva contrasenya',
          'signup.title': 'Crear un compte',
          'signup.email': 'Correu electrònic',
          'signup.emailExists': 'El correu electrònic ja existeix',
          'signup.username': 'Nom d\'usuari',
          'signup.usernameError': 'El nom d\'usuari és incorrecte. Com a mínim 5 caràcters, sense espais i màxim 20 caràcters',
          'signup.usernameExists': 'El nom d\'usuari ja existeix',
          'signup.password': 'Contrasenya',
          'signup.confirmPassword': 'Confirmar contrasenya',
          'signup.submit': 'Crear compte',
          'signup.login': 'Ja tens un compte? Inicia sessió',
          'signup.passwordMismatch': 'Les contraseyes no coincideixen',
          'signup.passwordLength': 'La contrasenya ha de tenir almenys 6 caràcters',
          'signup.invalidEmail': 'Correu electrònic no vàlid',
          'signup.emptyFields': 'Tots els camps són obligatoris',
          'modal.close': 'Tancar',
          'modal.error': 'Error',
          'modal.success': 'Èxit',
          'modal.warning': 'Advertència',
          'modal.info': 'Informació',
          'modal.confirm': 'Confirmar',
          'modal.cancel': 'Cancel·lar',
          'modal.save': 'Desar',
          'modal.delete': 'Eliminar',
          'modal.edit': 'Editar',
          'categoria.title': 'Crear Categoria',
          'categoria.edit': 'Editar Categoria',
          'categoria.form.title': 'Títol',
          'categoria.form.description': 'Descripció',
          'categoria.form.fields': 'Camps',
          'categoria.form.addField': 'Afegir Camp',
          'categoria.form.fieldPlaceholder': 'Nom del camp',
          'categoria.form.save': 'Desar',
          'categoria.form.update': 'Actualitzar',
          'categoria.form.cancel': 'Cancel·lar',
          'categoria.form.back': 'Tornar',
          'categoria.form.field': 'camp',
          'categoria.form.fieldsPlural': 'camps',
          'categoria.error.server': 'Error del servidor',
          'categoria.error.unknown': 'Error desconegut',
          'categoria.error.loading': 'Error en carregar la categoria',
          'categoria.error.saving': 'Error en desar la categoria',
          'categoria.validation.emptyFields': 'Els camps no poden estar buits',
          'categoria.success.created': 'Categoria creada correctament',
          'categoria.success.updated': 'Categoria actualitzada correctament',
          'categoria.list.title': 'Llista de Categories',
          'categoria.list.add': 'Afegir Categoria',
          'categoria.list.loading': 'Carregant categories...',
          'categoria.list.error': 'Error en carregar les categories:',
          'categoria.list.empty': 'No hi ha categories disponibles',
          'categoria.list.delete.title': 'Està segur?',
          'categoria.list.delete.text': 'Aquesta acció eliminarà la categoria permanentment',
          'categoria.list.delete.confirm': 'Sí, eliminar',
          'categoria.list.delete.cancel': 'Cancel·lar',
          'categoria.list.delete.success': 'Categoria eliminada amb èxit',
          'categoria.list.delete.error': 'Error en eliminar la categoria',
          'navigation.static': 'Enllaços Estàtics',
          'navigation.dynamic': 'Menú Contextual',
          'login.session_expired': 'Sessió expirada. Si us plau, iniciï sessió de nou.',
          'auth.access_denied': 'Accés denegat: El rol {role} no té permisos per accedir a aquesta pàgina.',
          'auth.login_required': 'Inicia sessió per continuar.',
          'auth.unexpected_error': 'Ha ocorregut un error inesperat.',
          'roles.ADMIN': 'Administrador',
          'roles.COMPRADOR': 'Comprador',
          'roles.VENDEDOR': 'Venedor',
          'roles.TRABAJADOR': 'Treballador',
          'header.welcome': 'Benvingut',
          'header.menu': 'Menú',
          'header.toggle_menu': 'Alternar menú',
          'route.home': 'Inici',
          'route.login': 'Iniciar sessió',
          'route.signup': 'Registrar-se',
          'route.profile': 'Perfil',
          'route.categories': 'Categories',
          'route.create_category': 'Crear Categoria',
          'route.edit_category': 'Editar Categoria',
          'error.404': 'Pàgina no trobada',
          'error.403': 'Accés prohibit',
          'error.500': 'Error del servidor',
          'error.generic': 'Alguna cosa ha anat malament',
          'actions.save': 'Desar',
          'actions.cancel': 'Cancel·lar',
          'actions.edit': 'Editar',
          'actions.delete': 'Eliminar',
          'actions.view': 'Veure',
          'actions.back': 'Tornar',
          'actions.next': 'Següent',
          'actions.previous': 'Anterior',
          'common.loading': 'Carregant...',
          'common.error': 'Error',
          'common.success': 'Èxit',
          'common.warning': 'Advertència',
          'common.info': 'Informació',
          'producto.title': 'Productes Disponibles',
          'producto.price': 'Preu',
          'producto.price.hint': 'Introdueix el preu amb fins a dos decimals (exemple: 19.99)',
          'producto.details.title': 'Detalls',
          'producto.brand': 'Marca',
          'producto.state': 'Estat',
          'producto.stock': 'Estoc',
          'producto.stock.available': '{count} disponibles',
          'producto.stock.unavailable': 'Sense estoc',
          'producto.action.details': 'Veure Detalls',
          'producto.action.buy': 'Comprar',
          'producto.action.enable': 'Activar Producte',
          'producto.action.disable': 'Desactivar Producte',
          'producto.action.delete': 'Eliminar',
          'producto.action.ownProduct': 'El Teu Producte',
          'producto.action.cantBuyOwn': 'No pots comprar el teu propi producte',
          'producto.offerTitle': 'Fer una Oferta',
          'producto.makeOffer': 'La teva oferta',
          'producto.offerHint': 'Introdueix l\'import que vols oferir per aquest producte',
          'producto.sendOffer': 'Enviar Oferta',
          'producto.offerMessage': 'M\'agradaria oferir {offerAmount} pel producte: {productTitle}',
          'chat.createError': 'No s\'ha pogut crear el xat. Si us plau, torna-ho a provar.',
          'chat.title': 'Xat amb el Venedor',
          'chat.title.asSeller': 'Xat amb el Comprador',
          'chat.withUser': 'Xatejant amb {userName}',
          'chat.withUser.buyer': 'Comprador: {userName}',
          'chat.withUser.seller': 'Venedor: {userName}',
          'chat.noMessages': 'Encara no hi ha missatges. Inicia la conversa!',
          'producto.delete.confirmTitle': 'Eliminar Producte',
          'producto.delete.confirmText': 'Estàs segur que vols eliminar aquest producte? Aquesta acció no es pot desfer.',
          'producto.delete.confirmButton': 'Sí, eliminar',
          'producto.delete.success': 'Producte Eliminat',
          'producto.delete.successMessage': 'El producte s\'ha eliminat correctament.',
          'producto.delete.errorMessage': 'S\'ha produït un error en eliminar el producte. Si us plau, torna-ho a provar.',
          'producto.loading': 'Carregant productes...',
          'producto.empty': 'No hi ha productes disponibles.',
          'producto.inStock': 'En Estoc',
          'producto.lowStock': 'Poques Unitats',
          'producto.outOfStock': 'Esgotat',
          'producto.details': 'Detalls',
          'producto.emptyDescription': 'No hi ha productes disponibles al nostre catàleg actualment. Si us plau, torni més tard o contacti amb suport per a més informació.',
          'producto.add.success': 'Producte Creat',
          'producto.add.successMessage': 'El teu producte s\'ha creat correctament.',
          'producto.add.error': 'Error',
          'producto.add.errorMessage': 'Hi ha hagut un error en crear el teu producte. Si us plau, torna-ho a provar.',
          'producto.validation.error': 'Error de Validació',
          'producto.validation.titleRequired': 'Si us plau, introdueix un títol pel producte.',
          'producto.validation.categoryRequired': 'Si us plau, selecciona una categoria.',
          'producto.validation.imageRequired': 'Si us plau, puja almenys una imatge del producte.',
          'producto.validation.brandRequired': 'Si us plau, introdueix una marca.',
          'producto.validation.descriptionRequired': 'Si us plau, introdueix una descripció del producte.',
          'producto.validation.priceRequired': 'Si us plau, introdueix un preu vàlid (més gran que 0).',
          'producto.validation.priceInvalid': 'El preu ha de ser almenys 0.01',
          'producto.validation.stockInvalid': 'L\'estoc no pot ser negatiu.',
          'producto.validation.categoryFieldsRequired': 'Si us plau, completa tots els camps específics de la categoria.',
          'producto.estado': 'Estat',
          'producto.estados.NUEVO': 'Nou',
          'producto.estados.COMONUEVO': 'Com Nou',
          'producto.estados.BUENESTADO': 'Bon Estat',
          'producto.estados.ACEPTABLE': 'Acceptable',
          'producto.estados.USADO': 'Usat',
          'producto.estados.REPARADO': 'Reparat',
          'producto.estados.REPARACIONESNECESARIAS': 'Reparacions Necessàries',
          'producto.estados.DESCONEGUT': 'Desconegut',
          'producto.add.back': 'Tornar a Productes',
          'producto.images': 'Imatges del Producte',
          'producto.direccion': 'Ubicació',
          'producto.actiu': 'Actiu',
          'producto.destacat': 'Destacat',
          'producto.category.fields': 'Camps Específics de la Categoria',
          'common.ok': 'Acceptar',
          'producto.direccionPlaceholder': 'Cerca ciutat o ubicació...',
          'producto.usarUbicacionActual': 'Utilitza la meva ubicació',
          'producto.ubicacion.obteniendo': 'Obtenint ubicació',
          'producto.ubicacion.espere': 'Si us plau, espera...',
          'producto.ubicacion.errorTitle': 'Error d\'ubicació',
          'producto.ubicacion.errorMessage': 'No s\'ha pogut obtenir la teva ubicació actual. Si us plau, comprova els permisos del dispositiu.',
          'producto.ubicacion.noSupported': 'La geolocalització no és compatible amb el teu navegador.',
          'producto.status.activated': 'El producte s\'ha activat correctament',
          'producto.status.deactivated': 'El producte s\'ha desactivat correctament',
          'producto.status.toggleError': 'S\'ha produït un error al canviar l\'estat del producte',
          'producto.details.loading': 'Carregant detalls del producte...',
          'common.notAvailable': 'No disponible',
          'common.yes': 'Sí',
          'common.no': 'No',
          'common.dates': 'Fechas',
          'common.createdOn': 'Creat el',
          'common.modifiedOn': 'Modificat el',
          'common.publishedOn': 'Publicat el',
          'common.cancel': 'Cancel·lar',
          'producto.edit.title': 'Editar Producte',
          'producto.edit.success': 'Producte Actualitzat',
          'producto.edit.successMessage': 'El teu producte s\'ha actualitzat correctament.',
          'producto.edit.error': 'Error d\'Actualització',
          'producto.edit.errorMessage': 'Hi ha hagut un error en actualitzar el teu producte. Si us plau, torna-ho a provar.',
          'producto.edit.loadError': 'Error de Càrrega',
          'producto.edit.loadErrorMessage': 'Hi ha hagut un error en carregar les dades del producte. Si us plau, torna-ho a provar.',
          'common.update': 'Actualitzar',
          'producto.action.edit': 'Editar Producte',
          'chat.typePlaceholder': 'Escriu un missatge...',
          'chat.send': 'Enviar',
          'chat.loading': 'Carregant missatges...',
          'chat.error': 'Error en carregar el xat',
          'chat.start': 'Iniciar Xat',
          'chat.loginRequired': 'Si us plau, inicia sessió per xatejar amb el venedor',
          'chat.contactSeller': 'Contactar amb el Venedor',
          'chat.buyerInitMessage': 'Hola, estic interessat en aquest producte.',
          'chat.list.title': 'Els meus Xats',
          'chat.list.empty': 'No s\'han trobat xats',
          'chat.list.emptyDescription': 'No tens converses actives. Explora productes i contacta amb un venedor per començar a xatejar.',
          'chat.list.browseProducts': 'Explorar Productes',
          'chat.viewChat': 'Veure Xat',
          'chat.unknownProduct': 'Producte Desconegut',
          'chat.list.loadError': 'Error en carregar els teus xats',
          'profile.title': 'Perfil d\'Usuari',
          'profile.account_info': 'Informació del Compte',
          'profile.username': 'Nom d\'Usuari',
          'profile.email': 'Correu Electrònic',
          'profile.role': 'Rol',
          'profile.edit_profile': 'Editar Perfil',
          'profile.new_password': 'Nova Contrasenya',
          'profile.confirm_password': 'Confirmar Contrasenya',
          'profile.password_note': 'Deixa en blanc per mantenir la teva contrasenya actual',
          'profile.save': 'Desar Canvis',
          'profile.cancel': 'Cancel·lar',
          'profile.account_actions': 'Accions del Compte',
          'profile.your_products': 'Els Teus Productes',
          'profile.add_product': 'Afegir Nou Producte',
          'profile.admin_actions': 'Accions d\'Administrador',
          'profile.manage_categories': 'Gestionar Categories',
          'profile.create_category': 'Crear Categoria',
          'profile.communication': 'Comunicació',
          'profile.view_chats': 'Veure Els Meus Xats',
          'profile.view_invoices': 'Veure Les Meves Factures',
          'invoice.title': 'Les Meves Factures',
          'profile.logout': 'Tancar Sessió',
          'profile.not_logged_in': 'No Has Iniciat Sessió',
          'profile.login_required_message': 'Necessites iniciar sessió per veure el teu perfil',
          'profile.login': 'Iniciar Sessió',
          'profile.signup': 'Registrar-se',
          'profile.ok': 'Acceptar',
          'profile.passwords_dont_match': 'Les contraseyes no coincideixen',
          'profile.invalid_email': 'Si us plau, introdueix un correu electrònic vàlid',
          'profile.update_success': 'Perfil actualitzat amb èxit',
          'profile.update_error': 'Error en actualitzar el perfil',
          'profile.login_error': 'Error en verificar l\'estat d\'inici de sessió',
          'profile.back_to_login': 'Tornar a Iniciar Sessió',
          'profile.description': 'Descripció',
          'profile.description_placeholder': 'Escriu una breu descripció sobre tu...',
          'profile.profile_image': 'Imatge de Perfil',
          'profile.social_links': 'Xarxes Socials',
          'profile.add_social_link': 'Afegir Xarxa Social',
          'profile.no_description': 'Sense descripció',
          'profile.user_profile': 'Perfil d\'Usuari',
          'profile.user_products': 'Productes de {username}',
          'profile.view_profile': 'Veure Perfil',
          'profile.view_product': 'Veure Producte',
          'profile.send_message': 'Enviar Missatge',
          'profile.user_not_found': 'Usuari No Trobat',
          'profile.user_not_found_message': 'L\'usuari que busques no existeix o ha estat eliminat.',
          'profile.user_id_required': 'Es requereix ID d\'usuari',
          'profile.load_error': 'Error en carregar el perfil d\'usuari',
          'profile.no_products_for_chat': 'Aquest usuari no té productes per xatejar.',
          'producto.similarProducts': 'Productes Similars',
          'producto.filters.title': 'Filtrar Productes',
          'producto.filters.searchPlaceholder': 'Cerca per nom, marca, descripció...',
          'producto.filters.category': 'Categoria',
          'producto.filters.state': 'Estat',
          'producto.filters.location': 'Ubicació',
          'producto.filters.priceRange': 'Rang de Preu',
          'producto.filters.allCategories': 'Totes les Categories',
          'producto.filters.allStates': 'Tots els Estats',
          'producto.filters.allLocations': 'Totes les Ubicacions',
          'producto.filters.min': 'Mín',
          'producto.filters.max': 'Máx',
          'producto.resultsFound': 'resultats trobats',
          'producto.resetFilters': 'Reiniciar Filtres',
          'producto.emptyFilters': 'Cap producte coincideix amb els teus filtres',
          'producto.emptyFiltersDescription': 'Intenta ajustar els teus criteris de cerca o navega per tots els productes',
          'producto.priceRange': 'Rang de Preu',
          'links.producto.add': 'Afegir Producte',
          'profile.subscription': 'Subscripció',
          'profile.subscribe': 'Subscriure Premium',
          'profile.processing': 'Processant...',
          'profile.subscription_success': 'Pagament realitzat amb èxit',
          'profile.subscription_cancelled': 'Pagament cancel·lat',
          'profile.subscription_error': 'S\'ha produït un error en processar el teu pagament',
          'profile.subscription_url_error': 'S\'ha rebut una URL de sessió invàlida',
          'profile.premium_subscription': 'Subscripció Premium',
          'profile.premium_description': 'Actualitza a premium per accedir a característiques i beneficis exclusius.',
          'profile.premium_benefits': 'Beneficis Premium',
          'profile.premium_benefit1': 'Llistats de productes destacats',
          'profile.premium_benefit2': 'Suport prioritari',
          'profile.premium_benefit3': 'Analítiques avançades',
          'profile.subscription_success_message': 'El teu compte ha estat actualitzat a Premium',
          'profile.subscription_cancelled_message': 'Has cancel·lat el procés de pagament',
          'profile.subscription_update_error': 'No s\'ha pogut actualitzar el teu estat Premium',
          'profile.promo_code': 'Codi Promocional',
          'profile.promo_code_placeholder': 'Introdueix el teu codi promocional',
          'profile.have_promo': 'Tens un codi promocional?',
          'profile.hide_promo': 'Ocultar codi promocional',
          'profile.promo_code_valid': 'Codi promocional aplicat',
          'profile.promo_code_invalid': 'Codi promocional invàlid',
          'profile.promo_code_empty': 'Si us plau, introdueix un codi promocional',
          'profile.promo_code_error': 'Error en validar el codi promocional',
          'common.apply': 'Aplicar',
          'profile.subscription_options': 'Opcions de Subscripció',
          'profile.subscription_options_desc': 'Tria una opció de subscripció per convertir-te en venedor.',
          'profile.free_trial': 'Prova Gratuïta',
          'profile.free_trial_desc': 'Obtén accés a funcions de venedor durant 30 dies sense cost.',
          'profile.free_trial_success': 'Prova Gratuïta Activada',
          'profile.free_trial_success_message': 'El teu compte ha estat actualitzat a venedor per 30 dies.',
          'profile.premium_desc': 'Subscriu-te per obtenir totes les funcions premium.',
          'estadisticas.title': 'Estadístiques del Producte',
          'estadisticas.backToDashboard': 'Tornar al Dashboard',
          'estadisticas.loading': 'Carregant estadístiques del producte...',
          'estadisticas.error': 'Error en carregar les estadístiques',
          'estadisticas.brand': 'Marca',
          'estadisticas.model': 'Model',
          'estadisticas.condition': 'Estat',
          'estadisticas.price': 'Preu',
          'estadisticas.totalVisits': 'Visites Totals',
          'estadisticas.monthlyVisits': 'Visites Mensuals',
          'estadisticas.visitDetails': 'Detalls de Visites per Mes',
          'estadisticas.noData': 'No hi ha dades de visites registrades',
          'estadisticas.table.month': 'Mes',
          'estadisticas.table.year': 'Any',
          'estadisticas.table.visits': 'Visites',
          'estadisticas.table.lastUpdate': 'Última Actualització',
          'estadisticas.noVisits': 'No hi ha visites registrades per aquest producte',
          'dashboard.title': 'Tauler - Estadístiques de Visites',
          'dashboard.totalProducts': 'Total de Productes',
          'dashboard.totalVisits': 'Total de Visites',
          'dashboard.monthlyAverage': 'Mitjana Mensual',
          'dashboard.monthlyVisits': 'Visites Mensuals',
          'dashboard.topProducts': 'Productes més visitats',
          'dashboard.noProducts': 'No hi ha productes amb visites registrades',
          'dashboard.viewProduct': 'Veure Producte',
          'dashboard.year': 'Any',
          'dashboard.visits': 'Visites',
          'dashboard.refresh': 'Actualitzar',
          'dashboard.profile': 'Perfil',
          'months.january': 'Gener',
          'months.february': 'Febrer',
          'months.march': 'Març',
          'months.april': 'Abril',
          'months.may': 'Maig',
          'months.june': 'Juny',
          'months.july': 'Juliol',
          'months.august': 'Agost',
          'months.september': 'Setembre',
          'months.october': 'Octubre',
          'months.november': 'Novembre',
          'months.december': 'Desembre',
          'chat.delete': 'Eliminar Xat',
          'chat.delete.confirm': 'Estàs segur que vols eliminar aquest xat?',
          'chat.delete.success': 'Xat eliminat amb èxit',
          'chat.delete.error': 'Error en eliminar el xat',
          'chat.markAsSold': 'Marcar com Venut',
          'chat.markAsSold.confirm': 'Quantes unitats vols vendre?',
          'chat.markAsSold.quantity': 'Quantitat a vendre',
          'chat.markAsSold.success': 'Producte marcat com venut amb èxit',
          'chat.markAsSold.error': 'Error en marcar el producte com venut',
          'chat.productNotFound': 'Producte no trobat o ja no disponible',
          'profile.invoices': 'Factures',
          'invoice.as_buyer': 'Compres',
          'invoice.as_seller': 'Vendes',
          'invoice.no_invoices': 'No s\'han trobat factures',
          'invoice.loading_error': 'Error en carregar les factures',
          'invoice.product': 'Producte',
          'invoice.quantity': 'Quantitat',
          'invoice.amount': 'Import',
          'invoice.date': 'Data',
          'invoice.status': 'Estat',
          'invoice.actions': 'Accions',
          'invoice.view_details': 'Veure detalls',
          'invoice.details': 'Detalls de la Factura',
          'invoice.invoice_id': 'ID de Factura',
          'invoice.unit_price': 'Preu Unitari',
          'invoice.subtotal': 'Subtotal',
          'invoice.iva': 'IVA',
          'invoice.total': 'Total',
          'invoice.notes': 'Notes Addicionals',
          'invoice.status.pendiente': 'Pendent',
          'invoice.status.pagada': 'Pagada',
          'invoice.status.cancelada': 'Cancel·lada',
          'invoice.status.emitida': 'Emesa',
          'common.close': 'Tancar',
          'profile.username_changed_relogin': 'Nom d\'usuari canviat. S\'iniciarà sessió de nou.',
          'profile.relogin_required': 'Reinici de sessió necessari',
          'profile.username_changed_enter_password': 'El teu nom d\'usuari ha canviat. Si us plau, introdueix la teva contrasenya per iniciar sessió amb el nou nom d\'usuari.',
          'common.login': 'Iniciar sessió',
        }
      } as Translations
    };
  },
  actions: {
    setLanguage(lang: string) {
      this.currentLanguage = lang;
      // Save the language preference in cookies for 30 days
      Cookies.set('language', lang, { expires: 30, path: '/' });
    },
    t(key: string): string {
      return this.translations[this.currentLanguage][key] || key;
    }
  },
  getters: {
    getCurrentLanguage: (state) => {
      return state.currentLanguage;
    }
  }
});
export default useutf8Store;
