import { defineStore } from 'pinia';
import Cookies from 'js-cookie';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

export const useutf8Store = defineStore('utf8', {
  state: () => {
    // Check if language is stored in cookies, otherwise default to Spanish
    const savedLanguage = Cookies.get('language') || 'es';

    return {
      currentLanguage: savedLanguage,
      translations: {
        en: {
          'producto.add.title': 'Add New Product',
          'producto.add.step1': 'Title',
          'producto.add.step2': 'Category',
          'producto.add.step3': 'Images',
          'producto.add.step4': 'Details',
          'producto.titlePlaceholder': 'Enter product title',
          'producto.selectCategory': 'Select a category',
          'producto.addImage': 'Add image',
          'producto.category': 'Category',
          'producto.description': 'Description',
          'common.previous': 'Previous',
          'common.next': 'Next',
          'common.save': 'Save',
          'links.categoria.add': 'Add category',
          'links.categoria.list': 'Category list',
          'links.dashboard': 'Dashboard',
          'links.settings': 'Settings',
          'links.profile': 'Profile',
          'links.help': 'Help',
          'links.logout': 'Logout',
          'links.chat': 'My Chats',
          'login.title': 'Sign in to your account',
          'login.email': 'Email address',
          'login.username': 'Username',
          'login.usernamePassword': 'Username or password is incorrect',
          'login.password': 'Password',
          'login.allInputs': 'All fields are required. Please fill in all fields.',
          'login.remember': 'Remember me',
          'login.forgot': 'Forgot your password?',
          'login.submit': 'Sign in',
          'login.loginError': 'Login error',
          'language': 'Language',
          'language.en': 'English',
          'language.es': 'Spanish',
          'language.cat': 'Catalan',
          'language.select': 'Select your language',
          'login.login': 'Login',
          'login.register': 'Register',
          'login.forgotPassword': 'Forgot Password',
          'signup.title': 'Create an account',
          'signup.email': 'Email address',
          'signup.emailExists': 'Email already exists',
          'signup.username': 'Username',
          'signup.usernameError': 'Username is incorrect. Minimum 5 characters, no spaces and maximum 20 characters',
          'signup.usernameExists': 'Username already exists',
          'signup.password': 'Password',
          'signup.confirmPassword': 'Confirm Password',
          'signup.submit': 'Create Account',
          'signup.login': 'Already have an account? Sign in',
          'signup.passwordMismatch': 'Passwords do not match',
          'signup.passwordLength': 'Password must be at least 6 characters long',
          'signup.invalidEmail': 'Invalid email address',
          'signup.emptyFields': 'All fields are required',
          'modal.close': 'Close',
          'modal.error': 'Error',
          'modal.success': 'Success',
          'modal.warning': 'Warning',
          'modal.info': 'Information',
          'modal.confirm': 'Confirm',
          'modal.cancel': 'Cancel',
          'modal.save': 'Save',
          'modal.delete': 'Delete',
          'modal.edit': 'Edit',
          'categoria.title': 'Create Category',
          'categoria.edit': 'Edit Category',
          'categoria.form.title': 'Title',
          'categoria.form.description': 'Description',
          'categoria.form.fields': 'Fields',
          'categoria.form.addField': 'Add Field',
          'categoria.form.fieldPlaceholder': 'Field name',
          'categoria.form.save': 'Save',
          'categoria.form.update': 'Update',
          'categoria.form.cancel': 'Cancel',
          'categoria.form.back': 'Back',
          'categoria.form.field': 'field',
          'categoria.form.fieldsPlural': 'fields',
          'categoria.error.server': 'Server error',
          'categoria.error.unknown': 'Unknown error',
          'categoria.error.loading': 'Error loading category',
          'categoria.error.saving': 'Error saving category',
          'categoria.validation.emptyFields': 'Fields cannot be empty',
          'categoria.success.created': 'Category created successfully',
          'categoria.success.updated': 'Category updated successfully',
          'categoria.list.title': 'Categories List',
          'categoria.list.add': 'Add Category',
          'categoria.list.loading': 'Loading categories...',
          'categoria.list.error': 'Error loading categories:',
          'categoria.list.empty': 'No categories available',
          'categoria.list.delete.title': 'Are you sure?',
          'categoria.list.delete.text': 'This action will permanently delete the category',
          'categoria.list.delete.confirm': 'Yes, delete',
          'categoria.list.delete.cancel': 'Cancel',
          'categoria.list.delete.success': 'Category successfully deleted',
          'categoria.list.delete.error': 'Error deleting category',
          'navigation.static': 'Static Links',
          'navigation.dynamic': 'Context Menu',
          'login.session_expired': 'Session expired. Please log in again.',
          'auth.access_denied': 'Access denied: The role {role} does not have permission to access this page.',
          'auth.login_required': 'Please login to continue.',
          'auth.unexpected_error': 'Unexpected error occurred.',
          'roles.ADMIN': 'Administrator',
          'roles.COMPRADOR': 'Buyer',
          'roles.VENDEDOR': 'Seller',
          'roles.TRABAJADOR': 'Worker',
          'header.welcome': 'Welcome',
          'header.menu': 'Menu',
          'header.toggle_menu': 'Toggle menu',
          'route.home': 'Home',
          'route.login': 'Login',
          'route.signup': 'Sign up',
          'route.profile': 'Profile',
          'route.categories': 'Categories',
          'route.create_category': 'Create Category',
          'route.edit_category': 'Edit Category',
          'error.404': 'Page not found',
          'error.403': 'Forbidden',
          'error.500': 'Server error',
          'error.generic': 'Something went wrong',
          'actions.save': 'Save',
          'actions.cancel': 'Cancel',
          'actions.edit': 'Edit',
          'actions.delete': 'Delete',
          'actions.view': 'View',
          'actions.back': 'Back',
          'actions.next': 'Next',
          'actions.previous': 'Previous',
          'common.loading': 'Loading...',
          'common.error': 'Error',
          'common.success': 'Success',
          'common.warning': 'Warning',
          'common.info': 'Information',
          'producto.title': 'Available Products',
          'producto.price': 'Price',
          'producto.price.hint': 'Enter the price with up to two decimal places (example: 19.99)',
          'producto.details.title': 'Details',
          'producto.brand': 'Brand',
          'producto.state': 'State',
          'producto.stock': 'Stock',
          'producto.stock.available': '{count} available',
          'producto.stock.unavailable': 'Out of stock',
          'producto.action.details': 'View Details',
          'producto.action.buy': 'Buy',
          'producto.action.enable': 'Enable Product',
          'producto.action.disable': 'Disable Product',
          'producto.action.delete': 'Delete',
          'producto.action.ownProduct': 'Your Own Product',
          'producto.delete.confirmTitle': 'Delete Product',
          'producto.delete.confirmText': 'Are you sure you want to delete this product? This action cannot be undone.',
          'producto.delete.confirmButton': 'Yes, delete',
          'producto.delete.success': 'Product Deleted',
          'producto.delete.successMessage': 'The product has been successfully deleted.',
          'producto.delete.errorMessage': 'An error occurred while deleting the product. Please try again.',
          'producto.loading': 'Loading products...',
          'producto.empty': 'No products available.',
          'producto.inStock': 'In Stock',
          'producto.lowStock': 'Low Stock',
          'producto.outOfStock': 'Out of Stock',
          'producto.details': 'Details',
          'producto.emptyDescription': 'No products are currently available in our catalog. Please check back later or contact support for more information.',
          'producto.add.success': 'Product Created',
          'producto.add.successMessage': 'Your product has been created successfully.',
          'producto.add.error': 'Error',
          'producto.add.errorMessage': 'There was an error creating your product. Please try again.',
          'producto.validation.error': 'Validation Error',
          'producto.validation.titleRequired': 'Please enter a product title.',
          'producto.validation.categoryRequired': 'Please select a category.',
          'producto.validation.imageRequired': 'Please upload at least one product image.',
          'producto.validation.brandRequired': 'Please enter a brand name.',
          'producto.validation.descriptionRequired': 'Please enter a product description.',
          'producto.validation.priceRequired': 'Please enter a valid price (greater than 0).',
          'producto.validation.priceInvalid': 'Price must be at least 0.01',
          'producto.validation.stockInvalid': 'Stock cannot be negative.',
          'producto.validation.categoryFieldsRequired': 'Please complete all category-specific fields.',
          'producto.estado': 'Condition',
          'producto.estados.NUEVO': 'New',
          'producto.estados.COMONUEVO': 'Like New',
          'producto.estados.BUENESTADO': 'Good Condition',
          'producto.estados.ACEPTABLE': 'Acceptable',
          'producto.estados.USADO': 'Used',
          'producto.estados.REPARADO': 'Repaired',
          'producto.estados.REPARACIONESNECESARIAS': 'Repairs Needed',
          'producto.estados.DESCONOCIDO': 'Unknown',
          'producto.add.back': 'Back to Products',
          'producto.images': 'Product Images',
          'producto.direccion': 'Location',
          'producto.activo': 'Active',
          'producto.destacado': 'Featured',
          'producto.category.fields': 'Category Specific Fields',
          'common.ok': 'OK',
          'producto.direccionPlaceholder': 'Search city or location...',
          'producto.usarUbicacionActual': 'Use my location',
          'producto.ubicacion.obteniendo': 'Getting location',
          'producto.ubicacion.espere': 'Please wait...',
          'producto.ubicacion.errorTitle': 'Location Error',
          'producto.ubicacion.errorMessage': 'Could not get your current location. Please check your device permissions.',
          'producto.ubicacion.noSupported': 'Geolocation is not supported by your browser.',
          'producto.status.activated': 'Product has been successfully activated',
          'producto.status.deactivated': 'Product has been successfully deactivated',
          'producto.status.toggleError': 'An error occurred while changing product status',
          'producto.details.loading': 'Loading product details...',
          'common.notAvailable': 'Not available',
          'common.yes': 'Yes',
          'common.no': 'No',
          'common.dates': 'Dates',
          'common.createdOn': 'Created on',
          'common.modifiedOn': 'Modified on',
          'common.publishedOn': 'Published on',
          'common.cancel': 'Cancel',
          'producto.edit.title': 'Edit Product',
          'producto.edit.success': 'Product Updated',
          'producto.edit.successMessage': 'Your product has been updated successfully.',
          'producto.edit.error': 'Update Error',
          'producto.edit.errorMessage': 'There was an error updating your product. Please try again.',
          'producto.edit.loadError': 'Load Error',
          'producto.edit.loadErrorMessage': 'There was an error loading the product data. Please try again.',
          'common.update': 'Update',
          'producto.action.edit': 'Edit Product',
          'chat.title': 'Chat with Seller',
          'chat.noMessages': 'No messages yet. Start the conversation!',
          'chat.typePlaceholder': 'Type a message...',
          'chat.send': 'Send',
          'chat.loading': 'Loading messages...',
          'chat.error': 'Error loading chat',
          'chat.start': 'Start Chat',
          'chat.loginRequired': 'Please login to chat with the seller',
          'chat.contactSeller': 'Contact Seller',
          'chat.buyerInitMessage': 'Hi, I\'m interested in this product.',
          'chat.list.title': 'My Chats',
          'chat.list.empty': 'No chats found',
          'chat.list.emptyDescription': 'You don\'t have any active conversations. Browse products and contact a seller to start chatting.',
          'chat.list.browseProducts': 'Browse Products',
          'chat.viewChat': 'View Chat',
          'chat.unknownProduct': 'Unknown Product',
          'chat.list.loadError': 'Error loading your chats',
        },
        es: {
          'producto.add.title': 'Añadir Nuevo Producto',
          'producto.add.step1': 'Título',
          'producto.add.step2': 'Categoría',
          'producto.add.step3': 'Imágenes',
          'producto.add.step4': 'Detalles',
          'producto.titlePlaceholder': 'Introduce el título del producto',
          'producto.selectCategory': 'Selecciona una categoría',
          'producto.addImage': 'Añadir imagen',
          'producto.category': 'Categoría',
          'producto.description': 'Descripción',
          'common.previous': 'Anterior',
          'common.next': 'Siguiente',
          'common.save': 'Guardar',
          'links.categoria.add': 'Añadir categoría',
          'links.categoria.list': 'Lista de categorías',
          'links.dashboard': 'Panel de control',
          'links.settings': 'Configuración',
          'links.profile': 'Perfil',
          'links.help': 'Ayuda',
          'links.logout': 'Cerrar sesión',
          'links.chat': 'Mis Chats',
          'login.title': 'Iniciar sesión',
          'login.email': 'Correo electrónico',
          'login.username': 'Nombre de usuario',
          'login.usernamePassword': 'Nombre de usuario o contraseña incorrectos',
          'login.password': 'Contraseña',
          'login.allInputs': 'Todos los campos son obligatorios. Por favor, completa todos los campos.',
          'login.remember': 'Recordarme',
          'login.forgot': '¿Olvidaste tu contraseña?',
          'login.submit': 'Entrar',
          'login.loginError': 'Error al iniciar sesión',
          'language': 'Idioma',
          'language.en': 'Inglés',
          'language.es': 'Español',
          'language.cat': 'Catalán',
          'language.select': 'Selecciona tu idioma',
          'login.login': 'Iniciar sesión',
          'login.register': 'Registrar',
          'login.forgotPassword': 'Olvidé mi contraseña',
          'signup.title': 'Crear una cuenta',
          'signup.email': 'Correo electrónico',
          'signup.emailExists': 'El correo electrónico ya existe',
          'signup.username': 'Nombre de usuario',
          'signup.usernameError': 'El nombre de usuario es incorrecto. Mínimo 5 caracteres, sin espacios y máximo 20 caracteres',
          'signup.usernameExists': 'El nombre de usuario ya existe',
          'signup.password': 'Contraseña',
          'signup.confirmPassword': 'Confirmar contraseña',
          'signup.submit': 'Crear cuenta',
          'signup.login': '¿Ya tienes una cuenta? Inicia sesión',
          'signup.passwordMismatch': 'Las contraseñas no coinciden',
          'signup.passwordLength': 'La contraseña debe tener al menos 6 caracteres',
          'signup.invalidEmail': 'Correo electrónico no válido',
          'signup.emptyFields': 'Todos los campos son obligatorios',
          'modal.close': 'Cerrar',
          'modal.error': 'Error',
          'modal.success': 'Éxito',
          'modal.warning': 'Advertencia',
          'modal.info': 'Información',
          'modal.confirm': 'Confirmar',
          'modal.cancel': 'Cancelar',
          'modal.save': 'Guardar',
          'modal.delete': 'Eliminar',
          'modal.edit': 'Editar',
          'categoria.title': 'Crear Categoría',
          'categoria.edit': 'Editar Categoría',
          'categoria.form.title': 'Título',
          'categoria.form.description': 'Descripción',
          'categoria.form.fields': 'Campos',
          'categoria.form.addField': 'Añadir Campo',
          'categoria.form.fieldPlaceholder': 'Nombre del campo',
          'categoria.form.save': 'Guardar',
          'categoria.form.update': 'Actualizar',
          'categoria.form.cancel': 'Cancelar',
          'categoria.form.back': 'Volver',
          'categoria.form.field': 'campo',
          'categoria.form.fieldsPlural': 'campos',
          'categoria.error.server': 'Error del servidor',
          'categoria.error.unknown': 'Error desconocido',
          'categoria.error.loading': 'Error al cargar la categoría',
          'categoria.error.saving': 'Error al guardar la categoría',
          'categoria.validation.emptyFields': 'Los campos no pueden estar vacíos',
          'categoria.success.created': 'Categoría creada correctamente',
          'categoria.success.updated': 'Categoría actualizada correctamente',
          'categoria.list.title': 'Lista de Categorías',
          'categoria.list.add': 'Añadir Categoría',
          'categoria.list.loading': 'Cargando categorías...',
          'categoria.list.error': 'Error al cargar las categorías:',
          'categoria.list.empty': 'No hay categorías disponibles',
          'categoria.list.delete.title': '¿Está seguro?',
          'categoria.list.delete.text': 'Esta acción eliminará la categoría permanentemente',
          'categoria.list.delete.confirm': 'Sí, eliminar',
          'categoria.list.delete.cancel': 'Cancelar',
          'categoria.list.delete.success': 'Categoría eliminada exitosamente',
          'categoria.list.delete.error': 'Error al eliminar la categoría',
          'navigation.static': 'Enlaces Estáticos',
          'navigation.dynamic': 'Menú Contextual',
          'login.session_expired': 'Sesión expirada. Por favor, inicie sesión de nuevo.',
          'auth.access_denied': 'Acceso denegado: El rol {role} no tiene permisos para acceder a esta página.',
          'auth.login_required': 'Inicia sesión para continuar.',
          'auth.unexpected_error': 'Ha ocurrido un error inesperado.',
          'roles.ADMIN': 'Administrador',
          'roles.COMPRADOR': 'Comprador',
          'roles.VENDEDOR': 'Vendedor',
          'roles.TRABAJADOR': 'Trabajador',
          'header.welcome': 'Bienvenido',
          'header.menu': 'Menú',
          'header.toggle_menu': 'Alternar menú',
          'route.home': 'Inicio',
          'route.login': 'Iniciar sesión',
          'route.signup': 'Registrarse',
          'route.profile': 'Perfil',
          'route.categories': 'Categorías',
          'route.create_category': 'Crear Categoría',
          'route.edit_category': 'Editar Categoría',
          'error.404': 'Página no encontrada',
          'error.403': 'Acceso prohibido',
          'error.500': 'Error del servidor',
          'error.generic': 'Algo salió mal',
          'actions.save': 'Guardar',
          'actions.cancel': 'Cancelar',
          'actions.edit': 'Editar',
          'actions.delete': 'Eliminar',
          'actions.view': 'Ver',
          'actions.back': 'Volver',
          'actions.next': 'Siguiente',
          'actions.previous': 'Anterior',
          'common.loading': 'Cargando...',
          'common.error': 'Error',
          'common.success': 'Éxito',
          'common.warning': 'Advertencia',
          'common.info': 'Información',
          'producto.title': 'Productos Disponibles',
          'producto.price': 'Precio',
          'producto.price.hint': 'Introduce el precio con hasta dos decimales (ejemplo: 19.99)',
          'producto.details.title': 'Detalles',
          'producto.brand': 'Marca',
          'producto.state': 'Estado',
          'producto.stock': 'Stock',
          'producto.stock.available': '{count} disponibles',
          'producto.stock.unavailable': 'Sin stock',
          'producto.action.details': 'Ver Detalles',
          'producto.action.buy': 'Comprar',
          'producto.action.enable': 'Activar Producto',
          'producto.action.disable': 'Desactivar Producto',
          'producto.action.delete': 'Eliminar',
          'producto.action.ownProduct': 'Tu Propio Producto',
          'producto.delete.confirmTitle': 'Eliminar Producto',
          'producto.delete.confirmText': '¿Está seguro de que desea eliminar este producto? Esta acción no se puede deshacer.',
          'producto.delete.confirmButton': 'Sí, eliminar',
          'producto.delete.success': 'Producto Eliminado',
          'producto.delete.successMessage': 'El producto ha sido eliminado exitosamente.',
          'producto.delete.errorMessage': 'Ocurrió un error al eliminar el producto. Por favor, inténtelo nuevamente.',
          'producto.loading': 'Cargando productos...',
          'producto.empty': 'No hay productos disponibles.',
          'producto.inStock': 'En Stock',
          'producto.lowStock': 'Pocas Unidades',
          'producto.outOfStock': 'Agotado',
          'producto.details': 'Detalles',
          'producto.emptyDescription': 'No hay productos disponibles en nuestro catálogo actualmente. Por favor, vuelva más tarde o contacte con soporte para más información.',
          'producto.add.success': 'Producto Creado',
          'producto.add.successMessage': 'Tu producto ha sido creado exitosamente.',
          'producto.add.error': 'Error',
          'producto.add.errorMessage': 'Hubo un error al crear tu producto. Por favor, intenta nuevamente.',
          'producto.validation.error': 'Error de Validación',
          'producto.validation.titleRequired': 'Por favor, introduce un título para el producto.',
          'producto.validation.categoryRequired': 'Por favor, selecciona una categoría.',
          'producto.validation.imageRequired': 'Por favor, sube al menos una imagen del producto.',
          'producto.validation.brandRequired': 'Por favor, introduce una marca.',
          'producto.validation.descriptionRequired': 'Por favor, introduce una descripción del producto.',
          'producto.validation.priceRequired': 'Por favor, introduce un precio válido (mayor que 0).',
          'producto.validation.priceInvalid': 'El precio debe ser al menos 0.01',
          'producto.validation.stockInvalid': 'El stock no puede ser negativo.',
          'producto.validation.categoryFieldsRequired': 'Por favor, completa todos los campos específicos de la categoría.',
          'producto.estado': 'Estado',
          'producto.estados.NUEVO': 'Nuevo',
          'producto.estados.COMONUEVO': 'Como Nuevo',
          'producto.estados.BUENESTADO': 'Buen Estado',
          'producto.estados.ACEPTABLE': 'Aceptable',
          'producto.estados.USADO': 'Usado',
          'producto.estados.REPARADO': 'Reparado',
          'producto.estados.REPARACIONESNECESARIAS': 'Reparaciones Necesarias',
          'producto.estados.DESCONOCIDO': 'Desconocido',
          'producto.add.back': 'Volver a Productos',
          'producto.images': 'Imágenes del Producto',
          'producto.direccion': 'Ubicación',
          'producto.activo': 'Activo',
          'producto.destacado': 'Destacado',
          'producto.category.fields': 'Campos Específicos de la Categoría',
          'common.ok': 'Aceptar',
          'producto.direccionPlaceholder': 'Buscar ciudad o ubicación...',
          'producto.usarUbicacionActual': 'Usar mi ubicación',
          'producto.ubicacion.obteniendo': 'Obteniendo ubicación',
          'producto.ubicacion.espere': 'Por favor espere...',
          'producto.ubicacion.errorTitle': 'Error de ubicación',
          'producto.ubicacion.errorMessage': 'No se pudo obtener su ubicación actual. Por favor, compruebe los permisos de su dispositivo.',
          'producto.ubicacion.noSupported': 'La geolocalización no es compatible con su navegador.',
          'producto.status.activated': 'El producto ha sido activado exitosamente',
          'producto.status.deactivated': 'El producto ha sido desactivado exitosamente',
          'producto.status.toggleError': 'Ocurrió un error al cambiar el estado del producto',
          'producto.details.loading': 'Cargando detalles del producto...',
          'common.notAvailable': 'No disponible',
          'common.yes': 'Sí',
          'common.no': 'No',
          'common.dates': 'Fechas',
          'common.createdOn': 'Creado el',
          'common.modifiedOn': 'Modificado el',
          'common.publishedOn': 'Publicado el',
          'common.cancel': 'Cancelar',
          'producto.edit.title': 'Editar Producto',
          'producto.edit.success': 'Producto Actualizado',
          'producto.edit.successMessage': 'Tu producto ha sido actualizado exitosamente.',
          'producto.edit.error': 'Error de Actualización',
          'producto.edit.errorMessage': 'Hubo un error al actualizar tu producto. Por favor, intenta nuevamente.',
          'producto.edit.loadError': 'Error de Carga',
          'producto.edit.loadErrorMessage': 'Hubo un error al cargar los datos del producto. Por favor, intenta nuevamente.',
          'common.update': 'Actualizar',
          'producto.action.edit': 'Editar Producto',
          'chat.title': 'Chat con el Vendedor',
          'chat.noMessages': 'No hay mensajes aún. ¡Inicia la conversación!',
          'chat.typePlaceholder': 'Escribe un mensaje...',
          'chat.send': 'Enviar',
          'chat.loading': 'Cargando mensajes...',
          'chat.error': 'Error al cargar el chat',
          'chat.start': 'Iniciar Chat',
          'chat.loginRequired': 'Por favor, inicia sesión para chatear con el vendedor',
          'chat.contactSeller': 'Contactar al Vendedor',
          'chat.buyerInitMessage': 'Hola, estoy interesado en este producto.',
          'chat.list.title': 'Mis Chats',
          'chat.list.empty': 'No se encontraron chats',
          'chat.list.emptyDescription': 'No tienes conversaciones activas. Explora productos y contacta con un vendedor para comenzar a chatear.',
          'chat.list.browseProducts': 'Explorar Productos',
          'chat.viewChat': 'Ver Chat',
          'chat.unknownProduct': 'Producto Desconocido',
          'chat.list.loadError': 'Error al cargar tus chats',
        },
        cat: {
          'producto.add.title': 'Afegir Nou Producte',
          'producto.add.step1': 'Títol',
          'producto.add.step2': 'Categoria',
          'producto.add.step3': 'Imatges',
          'producto.add.step4': 'Detalls',
          'producto.titlePlaceholder': 'Introdueix el títol del producte',
          'producto.selectCategory': 'Selecciona una categoria',
          'producto.addImage': 'Afegir imatge',
          'producto.category': 'Categoria',
          'producto.description': 'Descripció',
          'common.previous': 'Anterior',
          'common.next': 'Següent',
          'common.save': 'Desar',
          'links.categoria.add': 'Afegir categoria',
          'links.categoria.list': 'Llista de categories',
          'links.dashboard': 'Tauler de control',
          'links.settings': 'Configuració',
          'links.profile': 'Perfil',
          'links.help': 'Ajuda',
          'links.logout': 'Tancar sessió',
          'links.chat': 'Els meus Xats',
          'login.title': 'Iniciar sessió',
          'login.email': 'Correu electrònic',
          'login.username': 'Nom d\'usuari',
          'login.password': 'Contrasenya',
          'login.usernamePassword': 'Nom d\'usuari o contrasenya incorrectes',
          'login.allInputs': 'Tots els camps són obligatoris. Si us plau, completa tots els camps.',
          'login.remember': 'Recorda\'m',
          'login.forgot': 'Has oblidat la teva contrasenya?',
          'login.submit': 'Entrar',
          'login.loginError': 'Error en iniciar sessió',
          'language': 'Idioma',
          'language.en': 'Anglès',
          'language.es': 'Espanyol',
          'language.cat': 'Català',
          'language.select': 'Selecciona el teu idioma',
          'login.login': 'Iniciar sessió',
          'login.register': 'Registrar',
          'login.forgotPassword': 'He oblidat la meva contrasenya',
          'signup.title': 'Crear un compte',
          'signup.email': 'Correu electrònic',
          'signup.emailExists': 'El correu electrònic ja existeix',
          'signup.username': 'Nom d\'usuari',
          'signup.usernameError': 'El nom d\'usuari és incorrecte. Com a mínim 5 caràcters, sense espais i màxim 20 caràcters',
          'signup.usernameExists': 'El nom d\'usuari ja existeix',
          'signup.password': 'Contrasenya',
          'signup.confirmPassword': 'Confirmar contrasenya',
          'signup.submit': 'Crear compte',
          'signup.login': 'Ja tens un compte? Inicia sessió',
          'signup.passwordMismatch': 'Les contrasenyes no coincideixen',
          'signup.passwordLength': 'La contrasenya ha de tenir almenys 6 caràcters',
          'signup.invalidEmail': 'Correu electrònic no vàlid',
          'signup.emptyFields': 'Tots els camps són obligatoris',
          'modal.close': 'Tancar',
          'modal.error': 'Error',
          'modal.success': 'Èxit',
          'modal.warning': 'Advertència',
          'modal.info': 'Informació',
          'modal.confirm': 'Confirmar',
          'modal.cancel': 'Cancel·lar',
          'modal.save': 'Desar',
          'modal.delete': 'Eliminar',
          'modal.edit': 'Editar',
          'categoria.title': 'Crear Categoria',
          'categoria.edit': 'Editar Categoria',
          'categoria.form.title': 'Títol',
          'categoria.form.description': 'Descripció',
          'categoria.form.fields': 'Camps',
          'categoria.form.addField': 'Afegir Camp',
          'categoria.form.fieldPlaceholder': 'Nom del camp',
          'categoria.form.save': 'Desar',
          'categoria.form.update': 'Actualitzar',
          'categoria.form.cancel': 'Cancel·lar',
          'categoria.form.back': 'Tornar',
          'categoria.form.field': 'camp',
          'categoria.form.fieldsPlural': 'camps',
          'categoria.error.server': 'Error del servidor',
          'categoria.error.unknown': 'Error desconegut',
          'categoria.error.loading': 'Error en carregar la categoria',
          'categoria.error.saving': 'Error en desar la categoria',
          'categoria.validation.emptyFields': 'Els camps no poden estar buits',
          'categoria.success.created': 'Categoria creada correctament',
          'categoria.success.updated': 'Categoria actualitzada correctament',
          'categoria.list.title': 'Llista de Categories',
          'categoria.list.add': 'Afegir Categoria',
          'categoria.list.loading': 'Carregant categories...',
          'categoria.list.error': 'Error en carregar les categories:',
          'categoria.list.empty': 'No hi ha categories disponibles',
          'categoria.list.delete.title': 'Està segur?',
          'categoria.list.delete.text': 'Aquesta acció eliminarà la categoria permanentment',
          'categoria.list.delete.confirm': 'Sí, eliminar',
          'categoria.list.delete.cancel': 'Cancel·lar',
          'categoria.list.delete.success': 'Categoria eliminada amb èxit',
          'categoria.list.delete.error': 'Error en eliminar la categoria',
          'navigation.static': 'Enllaços Estàtics',
          'navigation.dynamic': 'Menú Contextual',
          'login.session_expired': 'Sessió expirada. Si us plau, iniciï sessió de nou.',
          'auth.access_denied': 'Accés denegat: El rol {role} no té permisos per accedir a aquesta pàgina.',
          'auth.login_required': 'Inicia sessió per continuar.',
          'auth.unexpected_error': 'Ha ocorregut un error inesperat.',
          'roles.ADMIN': 'Administrador',
          'roles.COMPRADOR': 'Comprador',
          'roles.VENDEDOR': 'Venedor',
          'roles.TRABAJADOR': 'Treballador',
          'header.welcome': 'Benvingut',
          'header.menu': 'Menú',
          'header.toggle_menu': 'Alternar menú',
          'route.home': 'Inici',
          'route.login': 'Iniciar sessió',
          'route.signup': 'Registrar-se',
          'route.profile': 'Perfil',
          'route.categories': 'Categories',
          'route.create_category': 'Crear Categoria',
          'route.edit_category': 'Editar Categoria',
          'error.404': 'Pàgina no trobada',
          'error.403': 'Accés prohibit',
          'error.500': 'Error del servidor',
          'error.generic': 'Alguna cosa ha anat malament',
          'actions.save': 'Desar',
          'actions.cancel': 'Cancel·lar',
          'actions.edit': 'Editar',
          'actions.delete': 'Eliminar',
          'actions.view': 'Veure',
          'actions.back': 'Tornar',
          'actions.next': 'Següent',
          'actions.previous': 'Anterior',
          'common.loading': 'Carregant...',
          'common.error': 'Error',
          'common.success': 'Èxit',
          'common.warning': 'Advertència',
          'common.info': 'Informació',
          'producto.title': 'Productes Disponibles',
          'producto.price': 'Preu',
          'producto.price.hint': 'Introdueix el preu amb fins a dos decimals (exemple: 19.99)',
          'producto.details.title': 'Detalls',
          'producto.brand': 'Marca',
          'producto.state': 'Estat',
          'producto.stock': 'Estoc',
          'producto.stock.available': '{count} disponibles',
          'producto.stock.unavailable': 'Sense estoc',
          'producto.action.details': 'Veure Detalls',
          'producto.action.buy': 'Comprar',
          'producto.action.enable': 'Activar Producte',
          'producto.action.disable': 'Desactivar Producte',
          'producto.action.delete': 'Eliminar',
          'producto.action.ownProduct': 'El Teu Producte',
          'producto.delete.confirmTitle': 'Eliminar Producte',
          'producto.delete.confirmText': 'Estàs segur que vols eliminar aquest producte? Aquesta acció no es pot desfer.',
          'producto.delete.confirmButton': 'Sí, eliminar',
          'producto.delete.success': 'Producte Eliminat',
          'producto.delete.successMessage': 'El producte s\'ha eliminat correctament.',
          'producto.delete.errorMessage': 'S\'ha produït un error en eliminar el producte. Si us plau, torna-ho a provar.',
          'producto.loading': 'Carregant productes...',
          'producto.empty': 'No hi ha productes disponibles.',
          'producto.inStock': 'En Estoc',
          'producto.lowStock': 'Poques Unitats',
          'producto.outOfStock': 'Esgotat',
          'producto.details': 'Detalls',
          'producto.emptyDescription': 'No hi ha productes disponibles al nostre catàleg actualment. Si us plau, torni més tard o contacti amb suport per a més informació.',
          'producto.add.success': 'Producte Creat',
          'producto.add.successMessage': 'El teu producte s\'ha creat correctament.',
          'producto.add.error': 'Error',
          'producto.add.errorMessage': 'Hi ha hagut un error en crear el teu producte. Si us plau, torna-ho a provar.',
          'producto.validation.error': 'Error de Validació',
          'producto.validation.titleRequired': 'Si us plau, introdueix un títol pel producte.',
          'producto.validation.categoryRequired': 'Si us plau, selecciona una categoria.',
          'producto.validation.imageRequired': 'Si us plau, puja almenys una imatge del producte.',
          'producto.validation.brandRequired': 'Si us plau, introdueix una marca.',
          'producto.validation.descriptionRequired': 'Si us plau, introdueix una descripció del producte.',
          'producto.validation.priceRequired': 'Si us plau, introdueix un preu vàlid (més gran que 0).',
          'producto.validation.priceInvalid': 'El preu ha de ser almenys 0.01',
          'producto.validation.stockInvalid': 'L\'estoc no pot ser negatiu.',
          'producto.validation.categoryFieldsRequired': 'Si us plau, completa tots els camps específics de la categoria.',
          'producto.estado': 'Estat',
          'producto.estados.NUEVO': 'Nou',
          'producto.estados.COMONUEVO': 'Com Nou',
          'producto.estados.BUENESTADO': 'Bon Estat',
          'producto.estados.ACEPTABLE': 'Acceptable',
          'producto.estados.USADO': 'Usat',
          'producto.estados.REPARADO': 'Reparat',
          'producto.estados.REPARACIONESNECESARIAS': 'Reparacions Necessàries',
          'producto.estados.DESCONEGUT': 'Desconegut',
          'producto.add.back': 'Tornar a Productes',
          'producto.images': 'Imatges del Producte',
          'producto.direccion': 'Ubicació',
          'producto.actiu': 'Actiu',
          'producto.destacat': 'Destacat',
          'producto.category.fields': 'Camps Específics de la Categoria',
          'common.ok': 'Acceptar',
          'producto.direccionPlaceholder': 'Cerca ciutat o ubicació...',
          'producto.usarUbicacionActual': 'Utilitza la meva ubicació',
          'producto.ubicacion.obteniendo': 'Obtenint ubicació',
          'producto.ubicacion.espere': 'Si us plau, espera...',
          'producto.ubicacion.errorTitle': 'Error d\'ubicació',
          'producto.ubicacion.errorMessage': 'No s\'ha pogut obtenir la teva ubicació actual. Si us plau, comprova els permisos del dispositiu.',
          'producto.ubicacion.noSupported': 'La geolocalització no és compatible amb el teu navegador.',
          'producto.status.activated': 'El producte s\'ha activat correctament',
          'producto.status.deactivated': 'El producte s\'ha desactivat correctament',
          'producto.status.toggleError': 'S\'ha produït un error al canviar l\'estat del producte',
          'producto.details.loading': 'Carregant detalls del producte...',
          'common.notAvailable': 'No disponible',
          'common.yes': 'Sí',
          'common.no': 'No',
          'common.dates': 'Dates',
          'common.createdOn': 'Creat el',
          'common.modifiedOn': 'Modificat el',
          'common.publishedOn': 'Publicat el',
          'common.cancel': 'Cancel·lar',
          'producto.edit.title': 'Editar Producte',
          'producto.edit.success': 'Producte Actualitzat',
          'producto.edit.successMessage': 'El teu producte s\'ha actualitzat correctament.',
          'producto.edit.error': 'Error d\'Actualització',
          'producto.edit.errorMessage': 'Hi ha hagut un error en actualitzar el teu producte. Si us plau, torna-ho a provar.',
          'producto.edit.loadError': 'Error de Càrrega',
          'producto.edit.loadErrorMessage': 'Hi ha hagut un error en carregar les dades del producte. Si us plau, torna-ho a provar.',
          'common.update': 'Actualitzar',
          'producto.action.edit': 'Editar Producte',
          'chat.title': 'Xat amb el Venedor',
          'chat.noMessages': 'Encara no hi ha missatges. Inicia la conversa!',
          'chat.typePlaceholder': 'Escriu un missatge...',
          'chat.send': 'Enviar',
          'chat.loading': 'Carregant missatges...',
          'chat.error': 'Error en carregar el xat',
          'chat.start': 'Iniciar Xat',
          'chat.loginRequired': 'Si us plau, inicia sessió per xatejar amb el venedor',
          'chat.contactSeller': 'Contactar amb el Venedor',
          'chat.buyerInitMessage': 'Hola, estic interessat en aquest producte.',
          'chat.list.title': 'Els meus Xats',
          'chat.list.empty': 'No s\'han trobat xats',
          'chat.list.emptyDescription': 'No tens converses actives. Explora productes i contacta amb un venedor per començar a xatejar.',
          'chat.list.browseProducts': 'Explorar Productes',
          'chat.viewChat': 'Veure Xat',
          'chat.unknownProduct': 'Producte Desconegut',
          'chat.list.loadError': 'Error en carregar els teus xats',
        }
      } as Translations
    };
  },
  actions: {
    setLanguage(lang: string) {
      this.currentLanguage = lang;
      // Save the language preference in cookies for 30 days
      Cookies.set('language', lang, { expires: 30, path: '/' });
    },
    t(key: string): string {
      return this.translations[this.currentLanguage][key] || key;
    }
  },
  getters: {
    getCurrentLanguage: (state) => {
      return state.currentLanguage;
    }
  }
});
export default useutf8Store;
